p0_62 = [{
	"id": 1,
	"faction": "Lyonar Kingdoms",
	"rarity": "Basic",
	"name": "Argeon Highmayne",
	"description": "",
	"manaCost": 0,
	"type": "Unit",
	"race": "General",
	"attack": 2,
	"health": 25,
	"set": "Base"
}, {
	"id": 14,
	"faction": "Lyonar Kingdoms",
	"rarity": "Common",
	"name": "Silverguard Squire",
	"description": "",
	"manaCost": 1,
	"type": "Unit",
	"race": "Minion",
	"attack": 1,
	"health": 4,
	"set": "Base"
}, {
	"id": 9,
	"faction": "Lyonar Kingdoms",
	"rarity": "Basic",
	"name": "Windblade Adept",
	"description": "Zeal: Gains +2 Attack.",
	"manaCost": 2,
	"type": "Unit",
	"race": "Minion",
	"attack": 2,
	"health": 3,
	"set": "Base"
}, {
	"id": 10,
	"faction": "Lyonar Kingdoms",
	"rarity": "Epic",
	"name": "Sunstone Templar",
	"description": "Whenever this minion attacks or counterattacks an enemy minion or General, dispel that enemy.",
	"manaCost": 2,
	"type": "Unit",
	"race": "Minion",
	"attack": 1,
	"health": 4,
	"set": "Base"
}, {
	"id": 11,
	"faction": "Lyonar Kingdoms",
	"rarity": "Basic",
	"name": "Silverguard Knight",
	"description": "Provoke\nZeal: Gains +2 Attack.",
	"manaCost": 3,
	"type": "Unit",
	"race": "Minion",
	"attack": 1,
	"health": 5,
	"set": "Base"
}, {
	"id": 12,
	"faction": "Lyonar Kingdoms",
	"rarity": "Rare",
	"name": "Arclyte Sentinel",
	"description": "Opening Gambit: Give ANY nearby minion +2 Attack, but -2 Health.",
	"manaCost": 3,
	"type": "Unit",
	"race": "Minion",
	"attack": 2,
	"health": 4,
	"set": "Base"
}, {
	"id": 13,
	"faction": "Lyonar Kingdoms",
	"rarity": "Rare",
	"name": "Second Sun",
	"description": "Zeal: Gains +8 Attack.",
	"manaCost": 5,
	"type": "Unit",
	"race": "Minion",
	"attack": 0,
	"health": 8,
	"set": "Base"
}, {
	"id": 8,
	"faction": "Lyonar Kingdoms",
	"rarity": "Basic",
	"name": "Lysian Brawler",
	"description": "Celerity",
	"manaCost": 4,
	"type": "Unit",
	"race": "Minion",
	"attack": 4,
	"health": 4,
	"set": "Base"
}, {
	"id": 15,
	"faction": "Lyonar Kingdoms",
	"rarity": "Common",
	"name": "Lightchaser",
	"description": "Whenever ANY minion or General is healed, this minion gains +1/+1.",
	"manaCost": 2,
	"type": "Unit",
	"race": "Minion",
	"attack": 3,
	"health": 2,
	"set": "Base"
}, {
	"id": 16,
	"faction": "Lyonar Kingdoms",
	"rarity": "Common",
	"name": "Suntide Maiden",
	"description": "Zeal: At the end of your turn, restore this minion to full Health.",
	"manaCost": 4,
	"type": "Unit",
	"race": "Minion",
	"attack": 3,
	"health": 6,
	"set": "Base"
}, {
	"id": 17,
	"faction": "Lyonar Kingdoms",
	"rarity": "Rare",
	"name": "Ironcliffe Guardian",
	"description": "Airdrop, Provoke",
	"manaCost": 5,
	"type": "Unit",
	"race": "Spell",
	"attack": 3,
	"health": 10,
	"set": "Base"
}, {
	"id": 18,
	"faction": "Lyonar Kingdoms",
	"rarity": "Legendary",
	"name": "Elyx Stormblade",
	"description": "Provoke\nYour minions and General may move an additional space.",
	"manaCost": 6,
	"type": "Unit",
	"race": "Minion",
	"attack": 7,
	"health": 7,
	"set": "Base"
}, {
	"id": 20,
	"faction": "Lyonar Kingdoms",
	"rarity": "Legendary",
	"name": "Grandmaster Z'ir",
	"description": "When your General dies, Grandmaster Z'ir becomes your General.",
	"manaCost": 7,
	"type": "Unit",
	"race": "Minion",
	"attack": 5,
	"health": 12,
	"set": "Base"
}, {
	"id": 21,
	"faction": "Lyonar Kingdoms",
	"rarity": "Common",
	"name": "Azurite Lion",
	"description": "Celerity",
	"manaCost": 2,
	"type": "Unit",
	"race": "Minion",
	"attack": 2,
	"health": 3,
	"set": "Base"
}, {
	"id": 22,
	"faction": "Lyonar Kingdoms",
	"rarity": "Epic",
	"name": "Sunriser",
	"description": "Whenever ANY minion or General is healed, deal 2 damage to all nearby enemies.",
	"manaCost": 4,
	"type": "Unit",
	"race": "Minion",
	"attack": 3,
	"health": 4,
	"set": "Base"
}, {
	"id": 23,
	"faction": "Lyonar Kingdoms",
	"rarity": "Basic",
	"name": "Zir'An Sunforge",
	"description": "Bloodborn Spell: Restore 3 Health to any Minion.",
	"manaCost": 0,
	"type": "Unit",
	"race": "General",
	"attack": 2,
	"health": 25,
	"set": "Base"
}, {
	"id": 101,
	"faction": "Songhai Empire",
	"rarity": "Basic",
	"name": "Kaleos Xaan",
	"description": "",
	"manaCost": 0,
	"type": "Unit",
	"race": "General",
	"attack": 2,
	"health": 25,
	"set": "Base"
}, {
	"id": 108,
	"faction": "Songhai Empire",
	"rarity": "Common",
	"name": "Heartseeker",
	"description": "Ranged",
	"manaCost": 1,
	"type": "Unit",
	"race": "Minion",
	"attack": 1,
	"health": 1,
	"set": "Base"
}, {
	"id": 109,
	"faction": "Songhai Empire",
	"rarity": "Basic",
	"name": "Widowmaker",
	"description": "Ranged",
	"manaCost": 3,
	"type": "Unit",
	"race": "Minion",
	"attack": 2,
	"health": 3,
	"set": "Base"
}, {
	"id": 110,
	"faction": "Songhai Empire",
	"rarity": "Basic",
	"name": "Kaido Assassin",
	"description": "Backstab: (1).",
	"manaCost": 2,
	"type": "Unit",
	"race": "Minion",
	"attack": 2,
	"health": 3,
	"set": "Base"
}, {
	"id": 111,
	"faction": "Songhai Empire",
	"rarity": "Common",
	"name": "Scarlet Viper",
	"description": "Flying\nBackstab: (4).",
	"manaCost": 5,
	"type": "Unit",
	"race": "Minion",
	"attack": 2,
	"health": 5,
	"set": "Base"
}, {
	"id": 112,
	"faction": "Songhai Empire",
	"rarity": "Rare",
	"name": "Gore Horn",
	"description": "Backstab: (2).\nAfter this minion attacks, it gains +1/+1.",
	"manaCost": 3,
	"type": "Unit",
	"race": "Minion",
	"attack": 3,
	"health": 3,
	"set": "Base"
}, {
	"id": 114,
	"faction": "Songhai Empire",
	"rarity": "Common",
	"name": "Jade Monk",
	"description": "Whenever this minion takes damage, deal 1 damage to a random enemy minion.",
	"manaCost": 3,
	"type": "Unit",
	"race": "Minion",
	"attack": 4,
	"health": 3,
	"set": "Base"
}, {
	"id": 115,
	"faction": "Songhai Empire",
	"rarity": "Basic",
	"name": "Chakri Avatar",
	"description": "Whenever you cast a spell, this minion gains +1/+1.",
	"manaCost": 2,
	"type": "Unit",
	"race": "Arcanyst",
	"attack": 1,
	"health": 2,
	"set": "Base"
}, {
	"id": 116,
	"faction": "Songhai Empire",
	"rarity": "Rare",
	"name": "Four Winds Magi",
	"description": "Whenever you cast a spell, deal 1 damage to enemy General and restore 1 Health to your General.",
	"manaCost": 4,
	"type": "Unit",
	"race": "Arcanyst",
	"attack": 4,
	"health": 4,
	"set": "Base"
}, {
	"id": 117,
	"faction": "Songhai Empire",
	"rarity": "Rare",
	"name": "Celestial Phantom",
	"description": "Whenever this damages an enemy minion, destroy that minion.",
	"manaCost": 3,
	"type": "Unit",
	"race": "Minion",
	"attack": 1,
	"health": 5,
	"set": "Base"
}, {
	"id": 118,
	"faction": "Songhai Empire",
	"rarity": "Legendary",
	"name": "Storm Kage",
	"description": "Whenever one of your spells deals damage, put a Kage Lightning in your action bar.",
	"manaCost": 7,
	"type": "Unit",
	"race": "Minion",
	"attack": 5,
	"health": 10,
	"set": "Base"
}, {
	"id": 119,
	"faction": "Songhai Empire",
	"rarity": "Epic",
	"name": "Hamon Bladeseeker",
	"description": "At the start of your turn, deal 2 damage to your General.",
	"manaCost": 5,
	"type": "Unit",
	"race": "Minion",
	"attack": 8,
	"health": 8,
	"set": "Base"
}, {
	"id": 120,
	"faction": "Songhai Empire",
	"rarity": "Common",
	"name": "Keshrai Fanblade",
	"description": "Opening Gambit: Next turn, opponent's spells cost 2 more to cast.",
	"manaCost": 4,
	"type": "Unit",
	"race": "Minion",
	"attack": 5,
	"health": 3,
	"set": "Base"
}, {
	"id": 121,
	"faction": "Songhai Empire",
	"rarity": "Legendary",
	"name": "Tusk Boar",
	"description": "Rush\nReturn this minion to your action bar at the beginning of your next turn",
	"manaCost": 2,
	"type": "Unit",
	"race": "Minion",
	"attack": 3,
	"health": 3,
	"set": "Base"
}, {
	"id": 122,
	"faction": "Songhai Empire",
	"rarity": "Epic",
	"name": "Lantern Fox",
	"description": "Whenever this minion takes damage, put a Phoenix Fire in your action bar.",
	"manaCost": 3,
	"type": "Unit",
	"race": "Minion",
	"attack": 2,
	"health": 4,
	"set": "Base"
}, {
	"id": 123,
	"faction": "Songhai Empire",
	"rarity": "Basic",
	"name": "Reva Eventide",
	"description": "Bloodborn Spell: Summon a Heartseeker nearby your General.",
	"manaCost": 0,
	"type": "Unit",
	"race": "General",
	"attack": 2,
	"health": 25,
	"set": "Base"
}, {
	"id": 201,
	"faction": "Vetruvian Imperium",
	"rarity": "Basic",
	"name": "Zirix Starstrider",
	"description": "",
	"manaCost": 0,
	"type": "Unit",
	"race": "General",
	"attack": 2,
	"health": 25,
	"set": "Base"
}, {
	"id": 208,
	"faction": "Vetruvian Imperium",
	"rarity": "Basic",
	"name": "Wind Shrike",
	"description": "Flying\nDying Wish: Draw a card.",
	"manaCost": 4,
	"type": "Unit",
	"race": "Minion",
	"attack": 4,
	"health": 3,
	"set": "Base"
}, {
	"id": 209,
	"faction": "Vetruvian Imperium",
	"rarity": "Common",
	"name": "Starfire Scarab",
	"description": "Blast",
	"manaCost": 5,
	"type": "Unit",
	"race": "Minion",
	"attack": 4,
	"health": 7,
	"set": "Base"
}, {
	"id": 210,
	"faction": "Vetruvian Imperium",
	"rarity": "Rare",
	"name": "Sand Howler",
	"description": "Cannot be targeted by enemy spells.",
	"manaCost": 3,
	"type": "Unit",
	"race": "Dervish",
	"attack": 3,
	"health": 3,
	"set": "Base"
}, {
	"id": 211,
	"faction": "Vetruvian Imperium",
	"rarity": "Common",
	"name": "Dunecaster",
	"description": "Opening Gambit: Give +2/+2 to a friendly Dervish. If it is a Wind Dervish, it no longer disappears.",
	"manaCost": 2,
	"type": "Unit",
	"race": "Dervish",
	"attack": 2,
	"health": 1,
	"set": "Base"
}, {
	"id": 212,
	"faction": "Vetruvian Imperium",
	"rarity": "Common",
	"name": "Orb Weaver",
	"description": "Opening Gambit: Summon a copy of this minion on a nearby space.",
	"manaCost": 3,
	"type": "Unit",
	"race": "Dervish",
	"attack": 2,
	"health": 2,
	"set": "Base"
}, {
	"id": 213,
	"faction": "Vetruvian Imperium",
	"rarity": "Basic",
	"name": "Pyromancer",
	"description": "Blast",
	"manaCost": 2,
	"type": "Unit",
	"race": "Minion",
	"attack": 2,
	"health": 1,
	"set": "Base"
}, {
	"id": 214,
	"faction": "Vetruvian Imperium",
	"rarity": "Basic",
	"name": "Ethereal Obelysk",
	"description": "Summon Dervish",
	"manaCost": 2,
	"type": "Unit",
	"race": "Structure",
	"attack": 0,
	"health": 6,
	"set": "Base"
}, {
	"id": 215,
	"faction": "Vetruvian Imperium",
	"rarity": "Rare",
	"name": "Fireblaze Obelysk",
	"description": "Summon Dervish\nGive all friendly Dervishes +1 Attack.",
	"manaCost": 3,
	"type": "Unit",
	"race": "Structure",
	"attack": 0,
	"health": 6,
	"set": "Base"
}, {
	"id": 216,
	"faction": "Vetruvian Imperium",
	"rarity": "Common",
	"name": "Windstorm Obelysk",
	"description": "Summon Dervish\nGive all friendly Dervishes +1 Health.",
	"manaCost": 3,
	"type": "Unit",
	"race": "Structure",
	"attack": 0,
	"health": 6,
	"set": "Base"
}, {
	"id": 218,
	"faction": "Vetruvian Imperium",
	"rarity": "Rare",
	"name": "Imperial Mechanyst",
	"description": "Opening Gambit: Repair all of your artifacts to full durability.",
	"manaCost": 3,
	"type": "Unit",
	"race": "Minion",
	"attack": 2,
	"health": 5,
	"set": "Base"
}, {
	"id": 219,
	"faction": "Vetruvian Imperium",
	"rarity": "Epic",
	"name": "Mirage Master",
	"description": "Opening Gambit: This minion transforms into a copy of an enemy minion.",
	"manaCost": 4,
	"type": "Unit",
	"race": "Minion",
	"attack": 1,
	"health": 1,
	"set": "Base"
}, {
	"id": 220,
	"faction": "Vetruvian Imperium",
	"rarity": "Legendary",
	"name": "Aymara Healer",
	"description": "Provoke\nDying Wish: Deal 5 damage to the enemy General. Restore 5 Health to your General.",
	"manaCost": 6,
	"type": "Unit",
	"race": "Minion",
	"attack": 5,
	"health": 5,
	"set": "Base"
}, {
	"id": 221,
	"faction": "Vetruvian Imperium",
	"rarity": "Epic",
	"name": "Portal Guardian",
	"description": "Frenzy\nWhenever you summon a minion, this minion gains +1 Attack.",
	"manaCost": 3,
	"type": "Unit",
	"race": "Minion",
	"attack": 0,
	"health": 6,
	"set": "Base"
}, {
	"id": 222,
	"faction": "Vetruvian Imperium",
	"rarity": "Legendary",
	"name": "Oserix",
	"description": "Flying\nDying Wish: Equip 2 random artifacts from your deck onto your General.",
	"manaCost": 7,
	"type": "Unit",
	"race": "Minion",
	"attack": 8,
	"health": 6,
	"set": "Base"
}, {
	"id": 223,
	"faction": "Vetruvian Imperium",
	"rarity": "Basic",
	"name": "Scioness Sajj",
	"description": "Bloodborn Spell: Your General deals double damage to minions this turn.",
	"manaCost": 0,
	"type": "Unit",
	"race": "General",
	"attack": 2,
	"health": 25,
	"set": "Base"
}, {
	"id": 301,
	"faction": "Abyssian Host",
	"rarity": "Basic",
	"name": "Lilithe Blightchaser",
	"description": "",
	"manaCost": 0,
	"type": "Unit",
	"race": "General",
	"attack": 2,
	"health": 25,
	"set": "Base"
}, {
	"id": 308,
	"faction": "Abyssian Host",
	"rarity": "Basic",
	"name": "Abyssal Crawler",
	"description": "Dying Wish: Turn this space into Shadow Creep.",
	"manaCost": 1,
	"type": "Unit",
	"race": "Minion",
	"attack": 2,
	"health": 1,
	"set": "Base"
}, {
	"id": 309,
	"faction": "Abyssian Host",
	"rarity": "Common",
	"name": "Abyssal Juggernaut",
	"description": "Whenever this minion destroys an enemy minion, turn that space into Shadow Creep.",
	"manaCost": 4,
	"type": "Unit",
	"race": "Minion",
	"attack": 3,
	"health": 6,
	"set": "Base"
}, {
	"id": 310,
	"faction": "Abyssian Host",
	"rarity": "Rare",
	"name": "Bloodmoon Priestess",
	"description": "Deathwatch: Summon a 1/1 Wraithling on a random nearby space.",
	"manaCost": 4,
	"type": "Unit",
	"race": "Minion",
	"attack": 3,
	"health": 3,
	"set": "Base"
}, {
	"id": 311,
	"faction": "Abyssian Host",
	"rarity": "Basic",
	"name": "Shadow Watcher",
	"description": "Deathwatch: Gains +1/+1.",
	"manaCost": 3,
	"type": "Unit",
	"race": "Minion",
	"attack": 2,
	"health": 2,
	"set": "Base"
}, {
	"id": 312,
	"faction": "Abyssian Host",
	"rarity": "Common",
	"name": "Deepfire Devourer",
	"description": "Frenzy\nOpening Gambit: Destroy friendly minions around it and gain +2/+2 for each minion.",
	"manaCost": 4,
	"type": "Unit",
	"race": "Minion",
	"attack": 4,
	"health": 4,
	"set": "Base"
}, {
	"id": 313,
	"faction": "Abyssian Host",
	"rarity": "Common",
	"name": "Blood Siren",
	"description": "Opening Gambit: Give a nearby enemy minion or General -2 Attack this turn.",
	"manaCost": 2,
	"type": "Unit",
	"race": "Minion",
	"attack": 3,
	"health": 2,
	"set": "Base"
}, {
	"id": 314,
	"faction": "Abyssian Host",
	"rarity": "Legendary",
	"name": "Vorpal Reaver",
	"description": "Celerity\nDying Wish: Summon six Wraithlings on random spaces.",
	"manaCost": 6,
	"type": "Unit",
	"race": "Minion",
	"attack": 6,
	"health": 6,
	"set": "Base"
}, {
	"id": 316,
	"faction": "Abyssian Host",
	"rarity": "Rare",
	"name": "Darkspine Elemental",
	"description": "Opening Gambit: Gains +2/+2 for each of your Shadow Creep.",
	"manaCost": 2,
	"type": "Unit",
	"race": "Minion",
	"attack": 1,
	"health": 1,
	"set": "Base"
}, {
	"id": 317,
	"faction": "Abyssian Host",
	"rarity": "Basic",
	"name": "Gloomchaser",
	"description": "Opening Gambit: Summon a 1/1 Wraithling in a random nearby space.",
	"manaCost": 2,
	"type": "Unit",
	"race": "Minion",
	"attack": 2,
	"health": 2,
	"set": "Base"
}, {
	"id": 318,
	"faction": "Abyssian Host",
	"rarity": "Rare",
	"name": "Shadowdancer",
	"description": "Deathwatch: Deal 1 damage to the enemy General, and restore 1 Health to your General.",
	"manaCost": 5,
	"type": "Unit",
	"race": "Minion",
	"attack": 4,
	"health": 4,
	"set": "Base"
}, {
	"id": 319,
	"faction": "Abyssian Host",
	"rarity": "Common",
	"name": "Nightsorrow Assassin",
	"description": "Opening Gambit: Destroy a nearby enemy minion with 2 or less Attack.",
	"manaCost": 3,
	"type": "Unit",
	"race": "Minion",
	"attack": 2,
	"health": 1,
	"set": "Base"
}, {
	"id": 320,
	"faction": "Abyssian Host",
	"rarity": "Legendary",
	"name": "Spectral Revenant",
	"description": "Rush\nWhenever this damages an enemy minion, deal 4 damage to the enemy General.",
	"manaCost": 7,
	"type": "Unit",
	"race": "Minion",
	"attack": 6,
	"health": 6,
	"set": "Base"
}, {
	"id": 321,
	"faction": "Abyssian Host",
	"rarity": "Epic",
	"name": "Black Solus",
	"description": "Whenever you summon a Wraithling, this gains +2/+2 Attack.",
	"manaCost": 5,
	"type": "Unit",
	"race": "Minion",
	"attack": 4,
	"health": 7,
	"set": "Base"
}, {
	"id": 322,
	"faction": "Abyssian Host",
	"rarity": "Epic",
	"name": "Reaper of the Nine Moons",
	"description": "Flying\nDying Wish: Summon a random minion from the opponent's deck on this space.",
	"manaCost": 5,
	"type": "Unit",
	"race": "Minion",
	"attack": 5,
	"health": 4,
	"set": "Base"
}, {
	"id": 323,
	"faction": "Abyssian Host",
	"rarity": "Basic",
	"name": "Cassyva Soulreaper",
	"description": "Bloodborn Spell: Deal 1 damage to a minion. If it dies this turn, the space turns into Shadow Creep.",
	"manaCost": 0,
	"type": "Unit",
	"race": "General",
	"attack": 2,
	"health": 25,
	"set": "Base"
}, {
	"id": 401,
	"faction": "Magmar Aspects",
	"rarity": "Basic",
	"name": "Vaath the Immortal",
	"description": "",
	"manaCost": 0,
	"type": "Unit",
	"race": "General",
	"attack": 2,
	"health": 25,
	"set": "Base"
}, {
	"id": 402,
	"faction": "Magmar Aspects",
	"rarity": "Basic",
	"name": "Earth Walker",
	"description": "Grow: +1/+1.",
	"manaCost": 3,
	"type": "Unit",
	"race": "Minion",
	"attack": 3,
	"health": 3,
	"set": "Base"
}, {
	"id": 403,
	"faction": "Magmar Aspects",
	"rarity": "Common",
	"name": "Grimrock",
	"description": "Grow: +2/+2.",
	"manaCost": 4,
	"type": "Unit",
	"race": "Minion",
	"attack": 3,
	"health": 4,
	"set": "Base"
}, {
	"id": 404,
	"faction": "Magmar Aspects",
	"rarity": "Common",
	"name": "Kolossus",
	"description": "Grow: +4/+4.",
	"manaCost": 5,
	"type": "Unit",
	"race": "Minion",
	"attack": 1,
	"health": 7,
	"set": "Base"
}, {
	"id": 405,
	"faction": "Magmar Aspects",
	"rarity": "Epic",
	"name": "Makantor Warbeast",
	"description": "Frenzy, Rush",
	"manaCost": 6,
	"type": "Unit",
	"race": "Minion",
	"attack": 4,
	"health": 4,
	"set": "Base"
}, {
	"id": 406,
	"faction": "Magmar Aspects",
	"rarity": "Basic",
	"name": "Phalanxar",
	"description": "",
	"manaCost": 2,
	"type": "Unit",
	"race": "Minion",
	"attack": 6,
	"health": 1,
	"set": "Base"
}, {
	"id": 407,
	"faction": "Magmar Aspects",
	"rarity": "Rare",
	"name": "Elucidator",
	"description": "Rush\nOpening Gambit: Deal 4 damage to your General.",
	"manaCost": 4,
	"type": "Unit",
	"race": "Minion",
	"attack": 5,
	"health": 4,
	"set": "Base"
}, {
	"id": 408,
	"faction": "Magmar Aspects",
	"rarity": "Rare",
	"name": "Unstable Leviathan",
	"description": "At the start of your turn, deal 4 damage to a random minion or General.",
	"manaCost": 7,
	"type": "Unit",
	"race": "Minion",
	"attack": 11,
	"health": 11,
	"set": "Base"
}, {
	"id": 409,
	"faction": "Magmar Aspects",
	"rarity": "Epic",
	"name": "Kujata",
	"description": "Your minions cost 1 less to summon and take 1 damage when summoned from your action bar.",
	"manaCost": 2,
	"type": "Unit",
	"race": "Minion",
	"attack": 2,
	"health": 2,
	"set": "Base"
}, {
	"id": 410,
	"faction": "Magmar Aspects",
	"rarity": "Basic",
	"name": "Primordial Gazer",
	"description": "Opening Gambit: Give a nearby friendly minion +2/+2.",
	"manaCost": 3,
	"type": "Unit",
	"race": "Minion",
	"attack": 2,
	"health": 2,
	"set": "Base"
}, {
	"id": 412,
	"faction": "Magmar Aspects",
	"rarity": "Common",
	"name": "Young Silithar",
	"description": "Rebirth",
	"manaCost": 2,
	"type": "Unit",
	"race": "Minion",
	"attack": 2,
	"health": 3,
	"set": "Base"
}, {
	"id": 413,
	"faction": "Magmar Aspects",
	"rarity": "Common",
	"name": "Veteran Silithar",
	"description": "Rebirth",
	"manaCost": 4,
	"type": "Unit",
	"race": "Minion",
	"attack": 4,
	"health": 5,
	"set": "Base"
}, {
	"id": 414,
	"faction": "Magmar Aspects",
	"rarity": "Legendary",
	"name": "Silithar Elder",
	"description": "Rebirth\nAt the end of your turn, summon a Silithar Elder Egg in a random nearby space.",
	"manaCost": 7,
	"type": "Unit",
	"race": "Minion",
	"attack": 8,
	"health": 8,
	"set": "Base"
}, {
	"id": 415,
	"faction": "Magmar Aspects",
	"rarity": "Rare",
	"name": "Spirit Harvester",
	"description": "At the end of your turn, deal 1 damage to ALL other minions.",
	"manaCost": 5,
	"type": "Unit",
	"race": "Minion",
	"attack": 5,
	"health": 5,
	"set": "Base"
}, {
	"id": 417,
	"faction": "Magmar Aspects",
	"rarity": "Legendary",
	"name": "Vindicator",
	"description": "Rush The first friendly minion summoned nearby this minion each turn gains Rush.",
	"manaCost": 3,
	"type": "Unit",
	"race": "Minion",
	"attack": 1,
	"health": 3,
	"set": "Base"
}, {
	"id": 418,
	"faction": "Magmar Aspects",
	"rarity": "Basic",
	"name": "Starhorn the Seeker",
	"description": "Bloodborn Spell: Both players draw a card.",
	"manaCost": 0,
	"type": "Unit",
	"race": "General",
	"attack": 2,
	"health": 25,
	"set": "Base"
}, {
	"id": 501,
	"faction": "Vanar Kindred",
	"rarity": "Basic",
	"name": "Faie Bloodwing",
	"description": "",
	"manaCost": 0,
	"type": "Unit",
	"race": "General",
	"attack": 2,
	"health": 25,
	"set": "Base"
}, {
	"id": 503,
	"faction": "Vanar Kindred",
	"rarity": "Basic",
	"name": "Fenrir Warmaster",
	"description": "Dying Wish: Summon a 3/2 Ghost Wolf on this space.",
	"manaCost": 3,
	"type": "Unit",
	"race": "Minion",
	"attack": 3,
	"health": 2,
	"set": "Base"
}, {
	"id": 505,
	"faction": "Vanar Kindred",
	"rarity": "Basic",
	"name": "Crystal Cloaker",
	"description": "Infiltrate: Gains +2 Attack.",
	"manaCost": 2,
	"type": "Unit",
	"race": "Vespyr",
	"attack": 2,
	"health": 3,
	"set": "Base"
}, {
	"id": 506,
	"faction": "Vanar Kindred",
	"rarity": "Common",
	"name": "Crystal Wisp",
	"description": "Dying Wish: Permanently gain 1 mana crystal.",
	"manaCost": 2,
	"type": "Unit",
	"race": "Minion",
	"attack": 1,
	"health": 1,
	"set": "Base"
}, {
	"id": 507,
	"faction": "Vanar Kindred",
	"rarity": "Epic",
	"name": "Frosthorn Rhyno",
	"description": "Infiltrate: Gains +1 Attack and Celerity.",
	"manaCost": 5,
	"type": "Unit",
	"race": "Minion",
	"attack": 6,
	"health": 5,
	"set": "Base"
}, {
	"id": 508,
	"faction": "Vanar Kindred",
	"rarity": "Epic",
	"name": "Draugar Lord",
	"description": "Dying Wish: Summon a 4/8 Ice Drake on this space.",
	"manaCost": 6,
	"type": "Unit",
	"race": "Vespyr",
	"attack": 4,
	"health": 8,
	"set": "Base"
}, {
	"id": 510,
	"faction": "Vanar Kindred",
	"rarity": "Rare",
	"name": "Snow Chaser",
	"description": "Infiltrate: When this minion dies, return it to your action bar.",
	"manaCost": 1,
	"type": "Unit",
	"race": "Vespyr",
	"attack": 2,
	"health": 1,
	"set": "Base"
}, {
	"id": 511,
	"faction": "Vanar Kindred",
	"rarity": "Common",
	"name": "Wolfraven",
	"description": "Flying\nInfiltrate: Gains +3 Attack.",
	"manaCost": 3,
	"type": "Unit",
	"race": "Minion",
	"attack": 1,
	"health": 4,
	"set": "Base"
}, {
	"id": 512,
	"faction": "Vanar Kindred",
	"rarity": "Common",
	"name": "Borean Bear",
	"description": "Whenever you summon a Vespyr minion, this minion gains +1 Attack.",
	"manaCost": 2,
	"type": "Unit",
	"race": "Vespyr",
	"attack": 1,
	"health": 3,
	"set": "Base"
}, {
	"id": 513,
	"faction": "Vanar Kindred",
	"rarity": "Rare",
	"name": "Razorback",
	"description": "Opening Gambit: Give all friendly minions +2 Attack this turn.",
	"manaCost": 4,
	"type": "Unit",
	"race": "Minion",
	"attack": 4,
	"health": 3,
	"set": "Base"
}, {
	"id": 514,
	"faction": "Vanar Kindred",
	"rarity": "Legendary",
	"name": "Ancient Grove",
	"description": "Provoke\nOpening Gambit: Your minions gain \"Dying Wish: Summon a 1/1 Treant with Provoke\".",
	"manaCost": 7,
	"type": "Unit",
	"race": "Vespyr",
	"attack": 7,
	"health": 7,
	"set": "Base"
}, {
	"id": 515,
	"faction": "Vanar Kindred",
	"rarity": "Legendary",
	"name": "Voice of the Wind",
	"description": "Whenever you summon a minion from your action bar, summon a 2/2 Vespyr Winter Maerid on a random nearby space.",
	"manaCost": 4,
	"type": "Unit",
	"race": "Minion",
	"attack": 4,
	"health": 4,
	"set": "Base"
}, {
	"id": 517,
	"faction": "Vanar Kindred",
	"rarity": "Common",
	"name": "Hearth-Sister",
	"description": "Opening Gambit: Switch positions with ANY other minion.",
	"manaCost": 2,
	"type": "Unit",
	"race": "Minion",
	"attack": 3,
	"health": 2,
	"set": "Base"
}, {
	"id": 519,
	"faction": "Vanar Kindred",
	"rarity": "Rare",
	"name": "Glacial Elemental",
	"description": "Whenever you summon a Vespyr minion, deal 2 damage to a random enemy minion.",
	"manaCost": 3,
	"type": "Unit",
	"race": "Vespyr",
	"attack": 2,
	"health": 3,
	"set": "Base"
}, {
	"id": 526,
	"faction": "Vanar Kindred",
	"rarity": "Basic",
	"name": "Arctic Displacer",
	"description": "Airdrop",
	"manaCost": 5,
	"type": "Unit",
	"race": "Vespyr",
	"attack": 10,
	"health": 4,
	"set": "Base"
}, {
	"id": 527,
	"faction": "Vanar Kindred",
	"rarity": "Basic",
	"name": "Kara Winterblade",
	"description": "Bloodborn Spell: Give each minion in your hand +1/+1.",
	"manaCost": 0,
	"type": "Unit",
	"race": "General",
	"attack": 2,
	"health": 25,
	"set": "Base"
}, {
	"id": 10001,
	"faction": "Neutral",
	"rarity": "Basic",
	"name": "Dragonlark",
	"description": "Flying",
	"manaCost": 1,
	"type": "Unit",
	"race": "Minion",
	"attack": 2,
	"health": 1,
	"set": "Base"
}, {
	"id": 10009,
	"faction": "Neutral",
	"rarity": "Rare",
	"name": "Silvertongue Corsair",
	"description": "Takes no damage from Generals.",
	"manaCost": 3,
	"type": "Unit",
	"race": "Minion",
	"attack": 3,
	"health": 3,
	"set": "Base"
}, {
	"id": 10012,
	"faction": "Neutral",
	"rarity": "Basic",
	"name": "Saberspine Tiger",
	"description": "Rush",
	"manaCost": 3,
	"type": "Unit",
	"race": "Minion",
	"attack": 4,
	"health": 1,
	"set": "Base"
}, {
	"id": 10013,
	"faction": "Neutral",
	"rarity": "Common",
	"name": "Blaze Hound",
	"description": "Opening Gambit: Both players draw a card.",
	"manaCost": 3,
	"type": "Unit",
	"race": "Minion",
	"attack": 4,
	"health": 3,
	"set": "Base"
}, {
	"id": 10014,
	"faction": "Neutral",
	"rarity": "Common",
	"name": "Sand Burrower",
	"description": "If this minion is dealt damage and survives, return it to your action bar.",
	"manaCost": 3,
	"type": "Unit",
	"race": "Minion",
	"attack": 2,
	"health": 4,
	"set": "Base"
}, {
	"id": 10016,
	"faction": "Neutral",
	"rarity": "Basic",
	"name": "Repulsor Beast",
	"description": "Opening Gambit: Push a nearby enemy minion to any space on the battlefield.",
	"manaCost": 3,
	"type": "Unit",
	"race": "Minion",
	"attack": 2,
	"health": 2,
	"set": "Base"
}, {
	"id": 10017,
	"faction": "Neutral",
	"rarity": "Basic",
	"name": "Fire Spitter",
	"description": "Ranged",
	"manaCost": 4,
	"type": "Unit",
	"race": "Minion",
	"attack": 3,
	"health": 2,
	"set": "Base"
}, {
	"id": 10018,
	"faction": "Neutral",
	"rarity": "Basic",
	"name": "Komodo Charger",
	"description": "",
	"manaCost": 1,
	"type": "Unit",
	"race": "Minion",
	"attack": 1,
	"health": 3,
	"set": "Base"
}, {
	"id": 10019,
	"faction": "Neutral",
	"rarity": "Basic",
	"name": "Planar Scout",
	"description": "Airdrop",
	"manaCost": 1,
	"type": "Unit",
	"race": "Minion",
	"attack": 2,
	"health": 1,
	"set": "Base"
}, {
	"id": 10020,
	"faction": "Neutral",
	"rarity": "Basic",
	"name": "Ephemeral Shroud",
	"description": "Opening Gambit: Dispel 1 nearby space.",
	"manaCost": 2,
	"type": "Unit",
	"race": "Minion",
	"attack": 2,
	"health": 2,
	"set": "Base"
}, {
	"id": 10021,
	"faction": "Neutral",
	"rarity": "Basic",
	"name": "Vale Hunter",
	"description": "Ranged",
	"manaCost": 2,
	"type": "Unit",
	"race": "Minion",
	"attack": 1,
	"health": 2,
	"set": "Base"
}, {
	"id": 10022,
	"faction": "Neutral",
	"rarity": "Epic",
	"name": "Twilight Sorcerer",
	"description": "Opening Gambit: Put a copy of a random spell you cast this game into your action bar.",
	"manaCost": 5,
	"type": "Unit",
	"race": "Minion",
	"attack": 3,
	"health": 6,
	"set": "Base"
}, {
	"id": 10204,
	"faction": "Neutral",
	"rarity": "Basic",
	"name": "Brightmoss Golem",
	"description": "",
	"manaCost": 5,
	"type": "Unit",
	"race": "Golem",
	"attack": 4,
	"health": 9,
	"set": "Base"
}, {
	"id": 10205,
	"faction": "Neutral",
	"rarity": "Basic",
	"name": "Bloodshard Golem",
	"description": "",
	"manaCost": 3,
	"type": "Unit",
	"race": "Golem",
	"attack": 4,
	"health": 3,
	"set": "Base"
}, {
	"id": 10206,
	"faction": "Neutral",
	"rarity": "Basic",
	"name": "Dragonbone Golem",
	"description": "",
	"manaCost": 7,
	"type": "Unit",
	"race": "Golem",
	"attack": 10,
	"health": 10,
	"set": "Base"
}, {
	"id": 10207,
	"faction": "Neutral",
	"rarity": "Basic",
	"name": "Stormmetal Golem",
	"description": "",
	"manaCost": 6,
	"type": "Unit",
	"race": "Golem",
	"attack": 8,
	"health": 8,
	"set": "Base"
}, {
	"id": 10301,
	"faction": "Neutral",
	"rarity": "Common",
	"name": "Sun Seer",
	"description": "Whenever this minion deals damage, restore 2 Health to your General.",
	"manaCost": 3,
	"type": "Unit",
	"race": "Arcanyst",
	"attack": 2,
	"health": 4,
	"set": "Base"
}, {
	"id": 10302,
	"faction": "Neutral",
	"rarity": "Rare",
	"name": "Manaforger",
	"description": "The first spell you cast each turn costs 1 less.",
	"manaCost": 2,
	"type": "Unit",
	"race": "Arcanyst",
	"attack": 1,
	"health": 3,
	"set": "Base"
}, {
	"id": 10303,
	"faction": "Neutral",
	"rarity": "Rare",
	"name": "Prismatic Illusionist",
	"description": "Whenever you cast a spell, summon a 2/1 Illusion on a random nearby space.",
	"manaCost": 3,
	"type": "Unit",
	"race": "Arcanyst",
	"attack": 2,
	"health": 3,
	"set": "Base"
}, {
	"id": 10304,
	"faction": "Neutral",
	"rarity": "Epic",
	"name": "Alcuin Loremaster",
	"description": "Opening Gambit: Put a copy of the most recently cast spell into your action bar.",
	"manaCost": 3,
	"type": "Unit",
	"race": "Arcanyst",
	"attack": 3,
	"health": 1,
	"set": "Base"
}, {
	"id": 10305,
	"faction": "Neutral",
	"rarity": "Rare",
	"name": "Owlbeast Sage",
	"description": "Whenever you cast a spell, your Arcanyst minions gain +2 Health.",
	"manaCost": 4,
	"type": "Unit",
	"race": "Arcanyst",
	"attack": 4,
	"health": 4,
	"set": "Base"
}, {
	"id": 10306,
	"faction": "Neutral",
	"rarity": "Rare",
	"name": "Lightbender",
	"description": "Opening Gambit: Dispel ALL spaces around it.",
	"manaCost": 4,
	"type": "Unit",
	"race": "Arcanyst",
	"attack": 3,
	"health": 3,
	"set": "Base"
}, {
	"id": 10307,
	"faction": "Neutral",
	"rarity": "Common",
	"name": "Serpenti",
	"description": "Frenzy",
	"manaCost": 6,
	"type": "Unit",
	"race": "Minion",
	"attack": 7,
	"health": 4,
	"set": "Base"
}, {
	"id": 19002,
	"faction": "Neutral",
	"rarity": "Common",
	"name": "Helm of MECHAZ0R",
	"description": "Opening Gambit: Progresses MECHAZ0R build by +20%.",
	"manaCost": 1,
	"type": "Unit",
	"race": "Mech",
	"attack": 2,
	"health": 2,
	"set": "Base"
}, {
	"id": 19003,
	"faction": "Neutral",
	"rarity": "Common",
	"name": "Wings of MECHAZ0R",
	"description": "Airdrop\nOpening Gambit: Progresses MECHAZ0R build by +20%.",
	"manaCost": 2,
	"type": "Unit",
	"race": "Mech",
	"attack": 1,
	"health": 4,
	"set": "Base"
}, {
	"id": 19004,
	"faction": "Neutral",
	"rarity": "Rare",
	"name": "Cannon of MECHAZ0R",
	"description": "Ranged\nOpening Gambit: Progresses MECHAZ0R build by +20%.",
	"manaCost": 3,
	"type": "Unit",
	"race": "Mech",
	"attack": 2,
	"health": 2,
	"set": "Base"
}, {
	"id": 19005,
	"faction": "Neutral",
	"rarity": "Rare",
	"name": "Sword of MECHAZ0R",
	"description": "Frenzy\nOpening Gambit: Progresses MECHAZ0R build by +20%.",
	"manaCost": 3,
	"type": "Unit",
	"race": "Mech",
	"attack": 3,
	"health": 3,
	"set": "Base"
}, {
	"id": 19006,
	"faction": "Neutral",
	"rarity": "Epic",
	"name": "Chassis of MECHAZ0R",
	"description": "Opening Gambit: Progresses MECHAZ0R build by +20%.\nCannot be targeted by ANY spells.",
	"manaCost": 4,
	"type": "Unit",
	"race": "Mech",
	"attack": 5,
	"health": 4,
	"set": "Base"
}, {
	"id": 19010,
	"faction": "Neutral",
	"rarity": "Common",
	"name": "Wind Stopper",
	"description": "Ranged attackers must attack this minion first.",
	"manaCost": 3,
	"type": "Unit",
	"race": "Minion",
	"attack": 1,
	"health": 7,
	"set": "Base"
}, {
	"id": 19025,
	"faction": "Neutral",
	"rarity": "Common",
	"name": "Swamp Entangler",
	"description": "Provoke",
	"manaCost": 1,
	"type": "Unit",
	"race": "Minion",
	"attack": 0,
	"health": 3,
	"set": "Base"
}, {
	"id": 19026,
	"faction": "Neutral",
	"rarity": "Basic",
	"name": "Rock Pulverizer",
	"description": "Provoke",
	"manaCost": 2,
	"type": "Unit",
	"race": "Minion",
	"attack": 1,
	"health": 4,
	"set": "Base"
}, {
	"id": 19027,
	"faction": "Neutral",
	"rarity": "Basic",
	"name": "Primus Shieldmaster",
	"description": "Provoke",
	"manaCost": 4,
	"type": "Unit",
	"race": "Minion",
	"attack": 3,
	"health": 6,
	"set": "Base"
}, {
	"id": 19028,
	"faction": "Neutral",
	"rarity": "Common",
	"name": "Fireblazer",
	"description": "Provoke",
	"manaCost": 5,
	"type": "Unit",
	"race": "Minion",
	"attack": 5,
	"health": 5,
	"set": "Base"
}, {
	"id": 19029,
	"faction": "Neutral",
	"rarity": "Common",
	"name": "Bluetip Scorpion",
	"description": "Deals double damage to minions.",
	"manaCost": 2,
	"type": "Unit",
	"race": "Minion",
	"attack": 3,
	"health": 1,
	"set": "Base"
}, {
	"id": 19030,
	"faction": "Neutral",
	"rarity": "Rare",
	"name": "Crimson Oculus",
	"description": "Whenever opponent summons a minion, this minion gains +1/+1.",
	"manaCost": 3,
	"type": "Unit",
	"race": "Minion",
	"attack": 2,
	"health": 3,
	"set": "Base"
}, {
	"id": 19031,
	"faction": "Neutral",
	"rarity": "Basic",
	"name": "Thorn Needler",
	"description": "",
	"manaCost": 4,
	"type": "Unit",
	"race": "Minion",
	"attack": 6,
	"health": 4,
	"set": "Base"
}, {
	"id": 19032,
	"faction": "Neutral",
	"rarity": "Common",
	"name": "Rogue Warden",
	"description": "Ranged",
	"manaCost": 5,
	"type": "Unit",
	"race": "Minion",
	"attack": 4,
	"health": 3,
	"set": "Base"
}, {
	"id": 19033,
	"faction": "Neutral",
	"rarity": "Basic",
	"name": "Putrid Dreadflayer",
	"description": "Flying",
	"manaCost": 3,
	"type": "Unit",
	"race": "Minion",
	"attack": 2,
	"health": 4,
	"set": "Base"
}, {
	"id": 19034,
	"faction": "Neutral",
	"rarity": "Basic",
	"name": "Young Flamewing",
	"description": "Flying",
	"manaCost": 4,
	"type": "Unit",
	"race": "Minion",
	"attack": 5,
	"health": 4,
	"set": "Base"
}, {
	"id": 19035,
	"faction": "Neutral",
	"rarity": "Common",
	"name": "Storm Aratha",
	"description": "Flying",
	"manaCost": 6,
	"type": "Unit",
	"race": "Minion",
	"attack": 6,
	"health": 5,
	"set": "Base"
}, {
	"id": 19036,
	"faction": "Neutral",
	"rarity": "Common",
	"name": "Whistling Blade",
	"description": "Provoke",
	"manaCost": 7,
	"type": "Unit",
	"race": "Minion",
	"attack": 2,
	"health": 15,
	"set": "Base"
}, {
	"id": 19037,
	"faction": "Neutral",
	"rarity": "Common",
	"name": "Primus Fist",
	"description": "Opening Gambit: Give a nearby friendly minion +2 Attack.",
	"manaCost": 2,
	"type": "Unit",
	"race": "Minion",
	"attack": 2,
	"health": 3,
	"set": "Base"
}, {
	"id": 19038,
	"faction": "Neutral",
	"rarity": "Rare",
	"name": "Golem Metallurgist",
	"description": "The first Golem you summon each turn costs 1 less.",
	"manaCost": 2,
	"type": "Unit",
	"race": "Golem",
	"attack": 2,
	"health": 3,
	"set": "Base"
}, {
	"id": 19039,
	"faction": "Neutral",
	"rarity": "Legendary",
	"name": "Golem Vanquisher",
	"description": "Provoke\nYour other Golem minions have Provoke.",
	"manaCost": 3,
	"type": "Unit",
	"race": "Golem",
	"attack": 2,
	"health": 4,
	"set": "Base"
}, {
	"id": 19040,
	"faction": "Neutral",
	"rarity": "Basic",
	"name": "Piercing Mantis",
	"description": "Frenzy",
	"manaCost": 2,
	"type": "Unit",
	"race": "Minion",
	"attack": 2,
	"health": 2,
	"set": "Base"
}, {
	"id": 19042,
	"faction": "Neutral",
	"rarity": "Common",
	"name": "Frostbone Naga",
	"description": "Opening Gambit: Deal 2 damage to ALL minions and Generals around it.",
	"manaCost": 4,
	"type": "Unit",
	"race": "Minion",
	"attack": 3,
	"health": 3,
	"set": "Base"
}, {
	"id": 19043,
	"faction": "Neutral",
	"rarity": "Legendary",
	"name": "Archon Spellbinder",
	"description": "Your opponent's spells cost 1 more to cast.",
	"manaCost": 6,
	"type": "Unit",
	"race": "Arcanyst",
	"attack": 7,
	"health": 9,
	"set": "Base"
}, {
	"id": 19044,
	"faction": "Neutral",
	"rarity": "Common",
	"name": "Silhouette Tracer",
	"description": "Opening Gambit: Teleport your General up to 3 spaces.",
	"manaCost": 4,
	"type": "Unit",
	"race": "Minion",
	"attack": 2,
	"health": 6,
	"set": "Base"
}, {
	"id": 19045,
	"faction": "Neutral",
	"rarity": "Legendary",
	"name": "Sarlac the Eternal",
	"description": "Dying Wish: Re-summon this minion on a random space.",
	"manaCost": 3,
	"type": "Unit",
	"race": "Minion",
	"attack": 1,
	"health": 1,
	"set": "Base"
}, {
	"id": 19046,
	"faction": "Neutral",
	"rarity": "Legendary",
	"name": "Dark Nemesis",
	"description": "At the start of your turn, deal 4 damage to the enemy General and this minion gains +4 Attack.",
	"manaCost": 7,
	"type": "Unit",
	"race": "Minion",
	"attack": 4,
	"health": 10,
	"set": "Base"
}, {
	"id": 19047,
	"faction": "Neutral",
	"rarity": "Legendary",
	"name": "Mirkblood Devourer",
	"description": "Friendly minions summoned nearby this minion gain +1/+1.",
	"manaCost": 3,
	"type": "Unit",
	"race": "Minion",
	"attack": 2,
	"health": 4,
	"set": "Base"
}, {
	"id": 19048,
	"faction": "Neutral",
	"rarity": "Basic",
	"name": "Skyrock Golem",
	"description": "",
	"manaCost": 2,
	"type": "Unit",
	"race": "Golem",
	"attack": 3,
	"health": 2,
	"set": "Base"
}, {
	"id": 19049,
	"faction": "Neutral",
	"rarity": "Rare",
	"name": "Sojourner",
	"description": "Whenever this minion deals damage, draw a card.",
	"manaCost": 3,
	"type": "Unit",
	"race": "Minion",
	"attack": 1,
	"health": 5,
	"set": "Base"
}, {
	"id": 19050,
	"faction": "Neutral",
	"rarity": "Rare",
	"name": "Azure Horn Shaman",
	"description": "Dying Wish: Give +4 Health to friendly minions around it.",
	"manaCost": 2,
	"type": "Unit",
	"race": "Minion",
	"attack": 1,
	"health": 4,
	"set": "Base"
}, {
	"id": 19051,
	"faction": "Neutral",
	"rarity": "Rare",
	"name": "Flameblood Warlock",
	"description": "Opening Gambit: Deal 3 damage to BOTH Generals.",
	"manaCost": 2,
	"type": "Unit",
	"race": "Minion",
	"attack": 3,
	"health": 1,
	"set": "Base"
}, {
	"id": 19052,
	"faction": "Neutral",
	"rarity": "Basic",
	"name": "Bloodtear Alchemist",
	"description": "Opening Gambit: Deal 1 damage to an enemy minion or General.",
	"manaCost": 1,
	"type": "Unit",
	"race": "Minion",
	"attack": 2,
	"health": 1,
	"set": "Base"
}, {
	"id": 10953,
	"faction": "Neutral",
	"rarity": "Rare",
	"name": "Crossbones",
	"description": "Opening Gambit: Destroy an enemy minion with Ranged.",
	"manaCost": 3,
	"type": "Unit",
	"race": "Minion",
	"attack": 3,
	"health": 3,
	"set": "Base"
}, {
	"id": 10954,
	"faction": "Neutral",
	"rarity": "Epic",
	"name": "Sworn Avenger",
	"description": "Ranged\nWhenever your General takes damage, this minion gains +1 Attack.",
	"manaCost": 3,
	"type": "Unit",
	"race": "Minion",
	"attack": 1,
	"health": 3,
	"set": "Base"
}, {
	"id": 10955,
	"faction": "Neutral",
	"rarity": "Epic",
	"name": "Sworn Defender",
	"description": "Whenever your General takes damage, restore this minion to full Health.",
	"manaCost": 5,
	"type": "Unit",
	"race": "Minion",
	"attack": 4,
	"health": 7,
	"set": "Base"
}, {
	"id": 10956,
	"faction": "Neutral",
	"rarity": "Legendary",
	"name": "Red Synja",
	"description": "Whenever your General takes damage, this minion deals 7 damage to a random nearby enemy minion.",
	"manaCost": 7,
	"type": "Unit",
	"race": "Minion",
	"attack": 7,
	"health": 7,
	"set": "Base"
}, {
	"id": 10957,
	"faction": "Neutral",
	"rarity": "Common",
	"name": "Rust Crawler",
	"description": "Opening Gambit: Destroy a random artifact on the enemy General.",
	"manaCost": 2,
	"type": "Unit",
	"race": "Minion",
	"attack": 2,
	"health": 3,
	"set": "Base"
}, {
	"id": 10958,
	"faction": "Neutral",
	"rarity": "Common",
	"name": "Dagger Kiri",
	"description": "Celerity",
	"manaCost": 5,
	"type": "Unit",
	"race": "Minion",
	"attack": 2,
	"health": 8,
	"set": "Base"
}, {
	"id": 10959,
	"faction": "Neutral",
	"rarity": "Common",
	"name": "Dancing Blades",
	"description": "Opening Gambit: Deal 3 damage to ANY minion in front of this minion.",
	"manaCost": 5,
	"type": "Unit",
	"race": "Minion",
	"attack": 4,
	"health": 6,
	"set": "Base"
}, {
	"id": 10960,
	"faction": "Neutral",
	"rarity": "Epic",
	"name": "Venom Toth",
	"description": "Whenever your opponent summons a minion, deal 1 damage to the enemy General.",
	"manaCost": 3,
	"type": "Unit",
	"race": "Minion",
	"attack": 3,
	"health": 3,
	"set": "Base"
}, {
	"id": 10961,
	"faction": "Neutral",
	"rarity": "Epic",
	"name": "Artifact Hunter",
	"description": "Opening Gambit: Draw a random artifact from your deck.",
	"manaCost": 4,
	"type": "Unit",
	"race": "Minion",
	"attack": 3,
	"health": 3,
	"set": "Base"
}, {
	"id": 10962,
	"faction": "Neutral",
	"rarity": "Epic",
	"name": "Chaos Elemental",
	"description": "Whenever this minion takes damage, it teleports to a random space.",
	"manaCost": 3,
	"type": "Unit",
	"race": "Minion",
	"attack": 4,
	"health": 4,
	"set": "Base"
}, {
	"id": 10963,
	"faction": "Neutral",
	"rarity": "Legendary",
	"name": "Jax Truesight",
	"description": "Ranged\nOpening Gambit: Summon a 1/1 Ranged Mini-Jax in each unoccupied corner.",
	"manaCost": 6,
	"type": "Unit",
	"race": "Minion",
	"attack": 1,
	"health": 1,
	"set": "Base"
}, {
	"id": 10965,
	"faction": "Neutral",
	"rarity": "Rare",
	"name": "Mindwarper",
	"description": "Opening Gambit: Gain a copy of a random spell from your opponent's action bar.",
	"manaCost": 4,
	"type": "Unit",
	"race": "Arcanyst",
	"attack": 4,
	"health": 3,
	"set": "Base"
}, {
	"id": 10966,
	"faction": "Neutral",
	"rarity": "Legendary",
	"name": "Pandora",
	"description": "At the end of your turn, summon a 3/3 Spirit Wolf with a random ability on a nearby space.",
	"manaCost": 7,
	"type": "Unit",
	"race": "Minion",
	"attack": 3,
	"health": 10,
	"set": "Base"
}, {
	"id": 10973,
	"faction": "Neutral",
	"rarity": "Epic",
	"name": "Lux Ignis",
	"description": "Ranged\nAt the end of your turn, restore 2 Health to all nearby friendly minions.",
	"manaCost": 5,
	"type": "Unit",
	"race": "Minion",
	"attack": 2,
	"health": 5,
	"set": "Base"
}, {
	"id": 10974,
	"faction": "Neutral",
	"rarity": "Epic",
	"name": "Syvrel the Exile",
	"description": "Ranged\nWhenever this minion damages an enemy minion, pull that minion in front of this one.",
	"manaCost": 3,
	"type": "Unit",
	"race": "Minion",
	"attack": 1,
	"health": 4,
	"set": "Base"
}, {
	"id": 10975,
	"faction": "Neutral",
	"rarity": "Legendary",
	"name": "Spelljammer",
	"description": "Each player draws an additional card at the end of their turns.",
	"manaCost": 3,
	"type": "Unit",
	"race": "Minion",
	"attack": 2,
	"health": 4,
	"set": "Base"
}, {
	"id": 10976,
	"faction": "Neutral",
	"rarity": "Epic",
	"name": "Dioltas",
	"description": "Dying Wish: Summon a 0/10 Tombstone minion with Provoke nearby your General.",
	"manaCost": 4,
	"type": "Unit",
	"race": "Minion",
	"attack": 5,
	"health": 2,
	"set": "Base"
}, {
	"id": 10978,
	"faction": "Neutral",
	"rarity": "Basic",
	"name": "Hailstone Golem",
	"description": "",
	"manaCost": 4,
	"type": "Unit",
	"race": "Golem",
	"attack": 4,
	"health": 6,
	"set": "Base"
}, {
	"id": 10979,
	"faction": "Neutral",
	"rarity": "Common",
	"name": "Maw",
	"description": "Opening Gambit: Deal 2 damage to a nearby enemy minion.",
	"manaCost": 2,
	"type": "Unit",
	"race": "Minion",
	"attack": 2,
	"health": 2,
	"set": "Base"
}, {
	"id": 10980,
	"faction": "Neutral",
	"rarity": "Common",
	"name": "Deathblighter",
	"description": "Opening Gambit: Deal 3 damage to all enemy minions around it.",
	"manaCost": 6,
	"type": "Unit",
	"race": "Minion",
	"attack": 3,
	"health": 4,
	"set": "Base"
}, {
	"id": 10981,
	"faction": "Neutral",
	"rarity": "Basic",
	"name": "Healing Mystic",
	"description": "Opening Gambit: Restore 2 Health to a minion or General.",
	"manaCost": 2,
	"type": "Unit",
	"race": "Minion",
	"attack": 2,
	"health": 3,
	"set": "Base"
}, {
	"id": 10982,
	"faction": "Neutral",
	"rarity": "Common",
	"name": "Void Hunter",
	"description": "Dying Wish: Draw a card.",
	"manaCost": 3,
	"type": "Unit",
	"race": "Minion",
	"attack": 4,
	"health": 2,
	"set": "Base"
}, {
	"id": 10983,
	"faction": "Neutral",
	"rarity": "Common",
	"name": "Ash Mephyt",
	"description": "Opening Gambit: Summon two copies of this minion on random spaces.",
	"manaCost": 5,
	"type": "Unit",
	"race": "Minion",
	"attack": 2,
	"health": 3,
	"set": "Base"
}, {
	"id": 10984,
	"faction": "Neutral",
	"rarity": "Common",
	"name": "First Sword of Akrane",
	"description": "Your other minions have +1 Attack.",
	"manaCost": 6,
	"type": "Unit",
	"race": "Minion",
	"attack": 7,
	"health": 7,
	"set": "Base"
}, {
	"id": 10985,
	"faction": "Neutral",
	"rarity": "Common",
	"name": "The High Hand",
	"description": "Opening Gambit: Gains +1/+1 for each card in your opponent's action bar.",
	"manaCost": 5,
	"type": "Unit",
	"race": "Minion",
	"attack": 2,
	"health": 3,
	"set": "Base"
}, {
	"id": 10986,
	"faction": "Neutral",
	"rarity": "Legendary",
	"name": "Eclipse",
	"description": "Whenever this minion takes damage, it deals that much damage to the enemy General.",
	"manaCost": 6,
	"type": "Unit",
	"race": "Arcanyst",
	"attack": 3,
	"health": 7,
	"set": "Base"
}, {
	"id": 10987,
	"faction": "Neutral",
	"rarity": "Legendary",
	"name": "Lady Locke",
	"description": "Provoke\nOpening Gambit: Other minions you summon this turn gain +1/+1 and Provoke.",
	"manaCost": 3,
	"type": "Unit",
	"race": "Minion",
	"attack": 2,
	"health": 2,
	"set": "Base"
}, {
	"id": 10988,
	"faction": "Neutral",
	"rarity": "Epic",
	"name": "Moebius",
	"description": "At the start of your turn, restore this minion to full Health and switch its Attack and Health.",
	"manaCost": 4,
	"type": "Unit",
	"race": "Arcanyst",
	"attack": 3,
	"health": 5,
	"set": "Base"
}, {
	"id": 10989,
	"faction": "Neutral",
	"rarity": "Epic",
	"name": "Captain Hank Hart",
	"description": "Ranged\nWhenever this minion deals damage, restore that much Health to it.",
	"manaCost": 5,
	"type": "Unit",
	"race": "Minion",
	"attack": 2,
	"health": 4,
	"set": "Base"
}, {
	"id": 10990,
	"faction": "Neutral",
	"rarity": "Legendary",
	"name": "Rook",
	"description": "At the end of your turn, this minion gains a random Faction ability.",
	"manaCost": 7,
	"type": "Unit",
	"race": "Minion",
	"attack": 5,
	"health": 5,
	"set": "Base"
}, {
	"id": 10991,
	"faction": "Neutral",
	"rarity": "Epic",
	"name": "Purgatos, The Realmkeeper",
	"description": "Whenever this minion deals damage, either deal 3 damage to the enemy General OR restore 3 Health to your General.",
	"manaCost": 4,
	"type": "Unit",
	"race": "Minion",
	"attack": 3,
	"health": 4,
	"set": "Base"
}, {
	"id": 10992,
	"faction": "Neutral",
	"rarity": "Common",
	"name": "Songweaver",
	"description": "Opening Gambit: Give a nearby friendly minion +1/+1 and Flying.",
	"manaCost": 3,
	"type": "Unit",
	"race": "Minion",
	"attack": 2,
	"health": 2,
	"set": "Base"
}, {
	"id": 10993,
	"faction": "Neutral",
	"rarity": "Epic",
	"name": "Aethermaster",
	"description": "You may replace an additional card each turn.",
	"manaCost": 2,
	"type": "Unit",
	"race": "Arcanyst",
	"attack": 1,
	"health": 3,
	"set": "Base"
}, {
	"id": 10994,
	"faction": "Neutral",
	"rarity": "Legendary",
	"name": "Zen'Rui, The BlightSpawned",
	"description": "Opening Gambit: Take control of a nearby enemy minion with 2 or less Attack.",
	"manaCost": 5,
	"type": "Unit",
	"race": "Minion",
	"attack": 4,
	"health": 3,
	"set": "Base"
}, {
	"id": 10995,
	"faction": "Neutral",
	"rarity": "Rare",
	"name": "Emerald Rejuvenator",
	"description": "Opening Gambit: Restore 4 Health to your General.",
	"manaCost": 4,
	"type": "Unit",
	"race": "Minion",
	"attack": 3,
	"health": 3,
	"set": "Base"
}, {
	"id": 10996,
	"faction": "Neutral",
	"rarity": "Legendary",
	"name": "Zurael, the Lifegiver",
	"description": "Opening Gambit: Summon all friendly minions that were destroyed on your opponent's last turn on a random space.",
	"manaCost": 7,
	"type": "Unit",
	"race": "Minion",
	"attack": 4,
	"health": 7,
	"set": "Base"
}, {
	"id": 10997,
	"faction": "Neutral",
	"rarity": "Legendary",
	"name": "Paddo",
	"description": "Airdrop\nOpening Gambit: Push ALL nearby minions and Generals to random spaces on the battlefield.",
	"manaCost": 7,
	"type": "Unit",
	"race": "Minion",
	"attack": 12,
	"health": 6,
	"set": "Base"
}, {
	"id": 11001,
	"faction": "Neutral",
	"rarity": "Common",
	"name": "Amu",
	"description": "",
	"manaCost": 2,
	"type": "Unit",
	"race": "Battle Pet",
	"attack": 3,
	"health": 3,
	"set": "Denizens of Shim'Zar"

}, {
	"id": 11004,
	"faction": "Neutral",
	"rarity": "Common",
	"name": "Yun",
	"description": "",
	"manaCost": 3,
	"type": "Unit",
	"race": "Battle Pet",
	"attack": 5,
	"health": 4,
	"set": "Denizens of Shim'Zar"

}, {
	"id": 11006,
	"faction": "Neutral",
	"rarity": "Legendary",
	"name": "Black Locust",
	"description": "Flying\nAfter this minion moves, summon a Black Locust on a random nearby space.",
	"manaCost": 4,
	"type": "Unit",
	"race": "Minion",
	"attack": 2,
	"health": 2,
	"set": "Base"
}, {
	"id": 11007,
	"faction": "Neutral",
	"rarity": "Rare",
	"name": "Wind Runner",
	"description": "After this minion moves, give all friendly minions around it +1/+1.",
	"manaCost": 3,
	"type": "Unit",
	"race": "Minion",
	"attack": 3,
	"health": 3,
	"set": "Base"
}, {
	"id": 11008,
	"faction": "Neutral",
	"rarity": "Epic",
	"name": "Mogwai",
	"description": "After this minion moves, draw a card.",
	"manaCost": 3,
	"type": "Unit",
	"race": "Minion",
	"attack": 2,
	"health": 3,
	"set": "Base"
}, {
	"id": 11009,
	"faction": "Neutral",
	"rarity": "Common",
	"name": "Ghost Lynx",
	"description": "Opening Gambit: Teleport a nearby minion to a random space.",
	"manaCost": 2,
	"type": "Unit",
	"race": "Minion",
	"attack": 2,
	"health": 1,
	"set": "Base"
}, {
	"id": 11010,
	"faction": "Neutral",
	"rarity": "Epic",
	"name": "Grailmaster",
	"description": "Whenever you summon a minion, this minion gains a random keyword ability.",
	"manaCost": 7,
	"type": "Unit",
	"race": "Minion",
	"attack": 6,
	"health": 6,
	"set": "Base"
}, {
	"id": 11011,
	"faction": "Neutral",
	"rarity": "Rare",
	"name": "Firestarter",
	"description": "Whenever you cast a spell, summon a 1/1 Spellspark with Rush on a random nearby space.",
	"manaCost": 5,
	"type": "Unit",
	"race": "Arcanyst",
	"attack": 3,
	"health": 5,
	"set": "Base"
}, {
	"id": 11013,
	"faction": "Neutral",
	"rarity": "Legendary",
	"name": "Khymera",
	"description": "Whenever this minion takes damage, summon a random token minion nearby.",
	"manaCost": 8,
	"type": "Unit",
	"race": "Minion",
	"attack": 5,
	"health": 12,
	"set": "Base"
}, {
	"id": 11014,
	"faction": "Neutral",
	"rarity": "Common",
	"name": "Jaxi",
	"description": "Dying Wish: Summon a 1/1 Ranged Mini-Jax in a random unoccupied corner.",
	"manaCost": 2,
	"type": "Unit",
	"race": "Minion",
	"attack": 1,
	"health": 1,
	"set": "Base"
}, {
	"id": 11015,
	"faction": "Neutral",
	"rarity": "Common",
	"name": "Sun Elemental",
	"description": "Opening Gambit: Give two random friendly minions +2 Health.",
	"manaCost": 4,
	"type": "Unit",
	"race": "Minion",
	"attack": 3,
	"health": 3,
	"set": "Base"
}, {
	"id": 11016,
	"faction": "Neutral",
	"rarity": "Rare",
	"name": "Prophet of the White Palm",
	"description": "Opening Gambit: Prevent ALL spell damage until your next turn.",
	"manaCost": 1,
	"type": "Unit",
	"race": "Minion",
	"attack": 1,
	"health": 1,
	"set": "Base"
}, {
	"id": 11017,
	"faction": "Neutral",
	"rarity": "Epic",
	"name": "Araki Headhunter",
	"description": "Whenever you summon a minion with Opening Gambit from your action bar, this minion gains +2 Attack.",
	"manaCost": 2,
	"type": "Unit",
	"race": "Minion",
	"attack": 1,
	"health": 3,
	"set": "Base"
}, {
	"id": 11018,
	"faction": "Neutral",
	"rarity": "Legendary",
	"name": "Keeper of the Vale",
	"description": "Opening Gambit: Summon a random friendly minion destroyed this game nearby this minion.",
	"manaCost": 5,
	"type": "Unit",
	"race": "Minion",
	"attack": 3,
	"health": 4,
	"set": "Base"
}, {
	"id": 11019,
	"faction": "Neutral",
	"rarity": "Rare",
	"name": "White Widow",
	"description": "Whenever you replace a card, deal 2 damage to a random enemy minion or General.",
	"manaCost": 4,
	"type": "Unit",
	"race": "Minion",
	"attack": 3,
	"health": 4,
	"set": "Base"
}, {
	"id": 11020,
	"faction": "Neutral",
	"rarity": "Common",
	"name": "Wings of Paradise",
	"description": "Flying\nWhenever you replace a card, this minion gains +2 Attack this turn.",
	"manaCost": 3,
	"type": "Unit",
	"race": "Minion",
	"attack": 3,
	"health": 3,
	"set": "Base"
}, {
	"id": 11021,
	"faction": "Neutral",
	"rarity": "Legendary",
	"name": "Astral Crusader",
	"description": "Whenever you replace this card, it costs 1 less and gains +1/+1.",
	"manaCost": 7,
	"type": "Unit",
	"race": "Minion",
	"attack": 7,
	"health": 6,
	"set": "Base"
}, {
	"id": 11022,
	"faction": "Neutral",
	"rarity": "Epic",
	"name": "Dreamgazer",
	"description": "When you replace this card, summon it on a random nearby space. Your General takes 2 damage",
	"manaCost": 2,
	"type": "Unit",
	"race": "Minion",
	"attack": 2,
	"health": 2,
	"set": "Base"
}, {
	"id": 11023,
	"faction": "Neutral",
	"rarity": "Epic",
	"name": "Bonereaper",
	"description": "Provoke\nAt the end of your turn, deal 2 damage to all nearby enemy minions.",
	"manaCost": 6,
	"type": "Unit",
	"race": "Minion",
	"attack": 2,
	"health": 9,
	"set": "Base"
}, {
	"id": 11024,
	"faction": "Neutral",
	"rarity": "Legendary",
	"name": "Hollow Grovekeeper",
	"description": "Opening Gambit: Destroy ANY nearby minion with Provoke or Frenzy. If you do, this minion gains Provoke and Frenzy.",
	"manaCost": 5,
	"type": "Unit",
	"race": "Minion",
	"attack": 3,
	"health": 4,
	"set": "Base"
}, {
	"id": 11025,
	"faction": "Neutral",
	"rarity": "Rare",
	"name": "Tethermancer",
	"description": "Provoke\nDispel any minion that deals damage to this one.",
	"manaCost": 4,
	"type": "Unit",
	"race": "Minion",
	"attack": 1,
	"health": 6,
	"set": "Base"
}, {
	"id": 11026,
	"faction": "Neutral",
	"rarity": "Common",
	"name": "War Talon",
	"description": "Frenzy, Provoke",
	"manaCost": 7,
	"type": "Unit",
	"race": "Minion",
	"attack": 4,
	"health": 9,
	"set": "Base"
}, {
	"id": 11027,
	"faction": "Neutral",
	"rarity": "Common",
	"name": "Sapphire Seer",
	"description": "Forcefield",
	"manaCost": 3,
	"type": "Unit",
	"race": "Minion",
	"attack": 2,
	"health": 2,
	"set": "Base"
}, {
	"id": 11028,
	"faction": "Neutral",
	"rarity": "Rare",
	"name": "Sunsteel Defender",
	"description": "Forcefield, Celerity",
	"manaCost": 5,
	"type": "Unit",
	"race": "Minion",
	"attack": 5,
	"health": 1,
	"set": "Base"
}, {
	"id": 11029,
	"faction": "Neutral",
	"rarity": "Legendary",
	"name": "E'Xun",
	"description": "Forcefield\nWhenever this minion attacks or is attacked, draw a card.",
	"manaCost": 7,
	"type": "Unit",
	"race": "Minion",
	"attack": 5,
	"health": 5,
	"set": "Base"
}, {
	"id": 11030,
	"faction": "Neutral",
	"rarity": "Epic",
	"name": "Sunset Paragon",
	"description": "Opening Gambit: ALL nearby minions deal damage to themselves equal to their Attack.",
	"manaCost": 5,
	"type": "Unit",
	"race": "Minion",
	"attack": 3,
	"health": 2,
	"set": "Base"
}, {
	"id": 11031,
	"faction": "Neutral",
	"rarity": "Basic",
	"name": "Necroseer",
	"description": "Dying Wish: Draw a card.",
	"manaCost": 5,
	"type": "Unit",
	"race": "Minion",
	"attack": 5,
	"health": 4,
	"set": "Base"
}, {
	"id": 11032,
	"faction": "Neutral",
	"rarity": "Basic",
	"name": "Bloodletter",
	"description": "Deals double damage to Generals.",
	"manaCost": 6,
	"type": "Unit",
	"race": "Minion",
	"attack": 4,
	"health": 6,
	"set": "Base"
}, {
	"id": 20028,
	"faction": "Vetruvian Imperium",
	"rarity": "Rare",
	"name": "Dominate Will",
	"description": "Take control of an enemy minion nearby your General.",
	"manaCost": 7,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"

}, {
	"id": 20043,
	"faction": "Lyonar Kingdoms",
	"rarity": "Common",
	"name": "Sundrop Elixir",
	"description": "Restore 5 Health to a minion or General.",
	"manaCost": 1,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20044,
	"faction": "Lyonar Kingdoms",
	"rarity": "Basic",
	"name": "Tempest",
	"description": "Deal 2 damage to ALL minions and Generals.",
	"manaCost": 2,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20045,
	"faction": "Lyonar Kingdoms",
	"rarity": "Common",
	"name": "Auryn Nexus",
	"description": "Give a friendly minion +3 Health.",
	"manaCost": 1,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20046,
	"faction": "Lyonar Kingdoms",
	"rarity": "Rare",
	"name": "Lasting Judgement",
	"description": "Give ANY minion +3 Attack, but -3 Health.",
	"manaCost": 2,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20047,
	"faction": "Lyonar Kingdoms",
	"rarity": "Basic",
	"name": "War Surge",
	"description": "Give all friendly minions +1/+1.",
	"manaCost": 2,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20049,
	"faction": "Abyssian Host",
	"rarity": "Basic",
	"name": "Daemonic Lure",
	"description": "Deal 1 damage to an enemy minion and teleport it to any space on the battlefield.",
	"manaCost": 2,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20050,
	"faction": "Abyssian Host",
	"rarity": "Legendary",
	"name": "Nether Summoning",
	"description": "Summon 2 random minions destroyed since your last turn on random spaces nearby your General.",
	"manaCost": 5,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20051,
	"faction": "Abyssian Host",
	"rarity": "Basic",
	"name": "Shadow Nova",
	"description": "Turn a 2x2 area into Shadow Creep.",
	"manaCost": 7,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20052,
	"faction": "Abyssian Host",
	"rarity": "Common",
	"name": "Void Pulse",
	"description": "Deal 2 damage to enemy General. Restore 3 Health to your General.",
	"manaCost": 1,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20057,
	"faction": "Abyssian Host",
	"rarity": "Rare",
	"name": "Ritual Banishing",
	"description": "Destroy a friendly minion to destroy an enemy minion.",
	"manaCost": 3,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20059,
	"faction": "Abyssian Host",
	"rarity": "Rare",
	"name": "Darkfire Sacrifice",
	"description": "Destroy a friendly minion. The next minion you summon costs 2 less.",
	"manaCost": 0,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20061,
	"faction": "Abyssian Host",
	"rarity": "Basic",
	"name": "Dark Transformation",
	"description": "Destroy an enemy minion and summon a 1/1 Wraithling on that space.",
	"manaCost": 5,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20062,
	"faction": "Lyonar Kingdoms",
	"rarity": "Rare",
	"name": "Lionheart Blessing",
	"description": "Give a friendly minion, \"Zeal: Whenever this minion deals damage, draw a card.\"",
	"manaCost": 1,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20063,
	"faction": "Magmar Aspects",
	"rarity": "Epic",
	"name": "Fractal Replication",
	"description": "Summon two copies of a friendly minion nearby that minion.",
	"manaCost": 6,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20064,
	"faction": "Lyonar Kingdoms",
	"rarity": "Common",
	"name": "Sun Bloom",
	"description": "Dispel a 2x2 area on the battlefield.",
	"manaCost": 2,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20065,
	"faction": "Abyssian Host",
	"rarity": "Common",
	"name": "Shadow Reflection",
	"description": "Give a friendly minion +5 Attack.",
	"manaCost": 3,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20066,
	"faction": "Lyonar Kingdoms",
	"rarity": "Basic",
	"name": "True Strike",
	"description": "Deal 2 damage to a minion.",
	"manaCost": 1,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20067,
	"faction": "Lyonar Kingdoms",
	"rarity": "Epic",
	"name": "Holy Immolation",
	"description": "Restore 4 Health to a friendly minion. Deal 4 damage to enemy minions and Generals around it.",
	"manaCost": 4,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20068,
	"faction": "Lyonar Kingdoms",
	"rarity": "Basic",
	"name": "Divine Bond",
	"description": "Give a minion +Attack equal to its Health.",
	"manaCost": 2,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20069,
	"faction": "Abyssian Host",
	"rarity": "Rare",
	"name": "Dark Seed",
	"description": "Deal 1 damage to the enemy General for each card in the opponent's action bar.",
	"manaCost": 4,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20070,
	"faction": "Abyssian Host",
	"rarity": "Common",
	"name": "Grasp of Agony",
	"description": "Choose an enemy minion. When it dies, it deals 3 damage to all enemy minions and Generals around it.",
	"manaCost": 1,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20071,
	"faction": "Abyssian Host",
	"rarity": "Basic",
	"name": "Soulshatter Pact",
	"description": "Give all friendly minions +2 Attack this turn.",
	"manaCost": 2,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20072,
	"faction": "Abyssian Host",
	"rarity": "Basic",
	"name": "Wraithling Swarm",
	"description": "Summon three 1/1 Wraithlings nearby each other.",
	"manaCost": 3,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20073,
	"faction": "Vetruvian Imperium",
	"rarity": "Common",
	"name": "Siphon Energy",
	"description": "Dispel an enemy minion.",
	"manaCost": 0,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20074,
	"faction": "Vetruvian Imperium",
	"rarity": "Basic",
	"name": "Cosmic Flesh",
	"description": "Give a friendly minion +1/+3 and Provoke.",
	"manaCost": 2,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20075,
	"faction": "Vetruvian Imperium",
	"rarity": "Basic",
	"name": "Blindscorch",
	"description": "Lower a minion's Attack to 0 until your next turn.",
	"manaCost": 1,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20076,
	"faction": "Vetruvian Imperium",
	"rarity": "Common",
	"name": "Astral Phasing",
	"description": "Give a friendly minion +5 Health and Flying.",
	"manaCost": 3,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20077,
	"faction": "Vetruvian Imperium",
	"rarity": "Basic",
	"name": "Entropic Decay",
	"description": "Destroy an enemy minion nearby your General.",
	"manaCost": 4,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20078,
	"faction": "Vetruvian Imperium",
	"rarity": "Legendary",
	"name": "Time Maelstrom",
	"description": "Reactivate your General.",
	"manaCost": 3,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20080,
	"faction": "Songhai Empire",
	"rarity": "Basic",
	"name": "Saberspine Seal",
	"description": "Give a minion or General +3 Attack this turn.",
	"manaCost": 1,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20081,
	"faction": "Songhai Empire",
	"rarity": "Basic",
	"name": "Phoenix Fire",
	"description": "Deal 3 damage to a minion or General.",
	"manaCost": 2,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20082,
	"faction": "Songhai Empire",
	"rarity": "Common",
	"name": "Twin Strike",
	"description": "Deal 2 damage to exactly two random enemy minions. Draw a card at end of turn.",
	"manaCost": 3,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20084,
	"faction": "Songhai Empire",
	"rarity": "Epic",
	"name": "Spiral Technique",
	"description": "Deal 8 damage to a minion or General.",
	"manaCost": 8,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20085,
	"faction": "Songhai Empire",
	"rarity": "Rare",
	"name": "Mana Vortex",
	"description": "The next spell you cast this turn costs 1 less. Draw a card at end of turn.",
	"manaCost": 0,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20086,
	"faction": "Songhai Empire",
	"rarity": "Basic",
	"name": "Inner Focus",
	"description": "Reactivate an exhausted friendly minion with 3 or less Attack.",
	"manaCost": 0,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20087,
	"faction": "Songhai Empire",
	"rarity": "Epic",
	"name": "Onyx Bear Seal",
	"description": "Transform an enemy minion into a 0/2 Panddo that cannot be attacked.",
	"manaCost": 3,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20088,
	"faction": "Songhai Empire",
	"rarity": "Basic",
	"name": "Ghost Lightning",
	"description": "Deal 1 damage to all enemy minions.",
	"manaCost": 1,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20089,
	"faction": "Abyssian Host",
	"rarity": "Epic",
	"name": "Wraithling Fury",
	"description": "Give a friendly Wraithling minion +4/+4.",
	"manaCost": 3,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20090,
	"faction": "Lyonar Kingdoms",
	"rarity": "Basic",
	"name": "Martyrdom",
	"description": "Destroy ANY minion. Restore that minion's Health to its General.",
	"manaCost": 3,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20093,
	"faction": "Vetruvian Imperium",
	"rarity": "Common",
	"name": "Sand Trap",
	"description": "Choose an enemy minion.  It can no longer move.",
	"manaCost": 2,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20094,
	"faction": "Songhai Empire",
	"rarity": "Rare",
	"name": "Deathstrike Seal",
	"description": "Give a friendly minion, \"Whenever this damages an enemy minion, destroy that minion.\"",
	"manaCost": 2,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20095,
	"faction": "Vetruvian Imperium",
	"rarity": "Basic",
	"name": "Scion's First Wish",
	"description": "Give a friendly minion +1/+1. Draw a card.",
	"manaCost": 1,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20096,
	"faction": "Vetruvian Imperium",
	"rarity": "Basic",
	"name": "Scion's Second Wish",
	"description": "Draw 2 cards.",
	"manaCost": 2,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20097,
	"faction": "Vetruvian Imperium",
	"rarity": "Legendary",
	"name": "Scion's Third Wish",
	"description": "Give a friendly Dervish minion +3/+3 and Blast",
	"manaCost": 3,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20099,
	"faction": "Vetruvian Imperium",
	"rarity": "Epic",
	"name": "Rasha's Curse",
	"description": "Destroy a random artifact on the enemy General. Summon a 2/2 Wind Dervish with Rush nearby the enemy General.",
	"manaCost": 2,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20100,
	"faction": "Songhai Empire",
	"rarity": "Common",
	"name": "Ancestral Divination",
	"description": "Whenever you summon a minion from your action bar this turn, draw a card.",
	"manaCost": 1,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20168,
	"faction": "Songhai Empire",
	"rarity": "Common",
	"name": "Mist Dragon Seal",
	"description": "Give a friendly minion +1/+1 and teleport it to any space on the battlefield.",
	"manaCost": 1,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20104,
	"faction": "Lyonar Kingdoms",
	"rarity": "Epic",
	"name": "Circle of Life",
	"description": "Deal 5 damage to an enemy minion. Restore 5 Health to your General.",
	"manaCost": 5,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20105,
	"faction": "Vetruvian Imperium",
	"rarity": "Epic",
	"name": "Stars' Fury",
	"description": "Summon a 2/2 Wind Dervish with Rush in front of each enemy minion and General.",
	"manaCost": 5,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20106,
	"faction": "Songhai Empire",
	"rarity": "Common",
	"name": "Artifact Defiler",
	"description": "Destroy all artifacts on the enemy General.",
	"manaCost": 2,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20109,
	"faction": "Lyonar Kingdoms",
	"rarity": "Common",
	"name": "Beam Shock",
	"description": "Stun an enemy minion or General.",
	"manaCost": 0,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20111,
	"faction": "Magmar Aspects",
	"rarity": "Basic",
	"name": "Dampening Wave",
	"description": "Choose an enemy minion. It can no longer counterattack.",
	"manaCost": 0,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20112,
	"faction": "Magmar Aspects",
	"rarity": "Rare",
	"name": "Flash Reincarnation",
	"description": "The next minion you summon this turn costs 2 less and takes 2 damage.",
	"manaCost": 0,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20113,
	"faction": "Magmar Aspects",
	"rarity": "Common",
	"name": "Diretide Frenzy",
	"description": "Give a friendly minion +1 Attack and Frenzy.",
	"manaCost": 1,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20114,
	"faction": "Magmar Aspects",
	"rarity": "Common",
	"name": "Tremor",
	"description": "Stun enemy minions in a 2x2 area.",
	"manaCost": 2,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20115,
	"faction": "Magmar Aspects",
	"rarity": "Basic",
	"name": "Dance of Dreams",
	"description": "Whenever a friendly minion dies this turn, draw a card.",
	"manaCost": 1,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20116,
	"faction": "Magmar Aspects",
	"rarity": "Basic",
	"name": "Greater Fortitude",
	"description": "Give a friendly minion +2/+2.",
	"manaCost": 1,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20117,
	"faction": "Magmar Aspects",
	"rarity": "Common",
	"name": "Earth Sphere",
	"description": "Restore 8 Health to your General.",
	"manaCost": 4,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20118,
	"faction": "Magmar Aspects",
	"rarity": "Epic",
	"name": "Bounded Lifeforce",
	"description": "Your General becomes 10/10.",
	"manaCost": 7,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20119,
	"faction": "Magmar Aspects",
	"rarity": "Common",
	"name": "Amplification",
	"description": "Give a friendly damaged minion +2 Attack and +4 Health.",
	"manaCost": 1,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20120,
	"faction": "Lyonar Kingdoms",
	"rarity": "Legendary",
	"name": "Aegis Barrier",
	"description": "Choose a friendly minion. It can't be targeted by enemy spells. Draw a card.",
	"manaCost": 1,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20121,
	"faction": "Magmar Aspects",
	"rarity": "Legendary",
	"name": "Metamorphosis",
	"description": "Transform all enemy minions into 1/1 Magma with no abilities until the end of your opponent's next turn.",
	"manaCost": 6,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20122,
	"faction": "Magmar Aspects",
	"rarity": "Basic",
	"name": "Plasma Storm",
	"description": "Destroy ALL minions with 3 or less Attack.",
	"manaCost": 5,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20124,
	"faction": "Magmar Aspects",
	"rarity": "Legendary",
	"name": "Chrysalis Burst",
	"description": "Summon a random Egg in 4 random spaces on the battlefield.",
	"manaCost": 4,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20125,
	"faction": "Magmar Aspects",
	"rarity": "Basic",
	"name": "Natural Selection",
	"description": "Destroy ANY minion with the lowest Attack or tied for the lowest Attack.",
	"manaCost": 2,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20128,
	"faction": "Lyonar Kingdoms",
	"rarity": "Legendary",
	"name": "Decimate",
	"description": "Destroy ALL minions that are not nearby any General.",
	"manaCost": 4,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20129,
	"faction": "Songhai Empire",
	"rarity": "Epic",
	"name": "Juxtaposition",
	"description": "Switch positions between ANY two minions.",
	"manaCost": 0,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20131,
	"faction": "Abyssian Host",
	"rarity": "Common",
	"name": "Breath Of The Unborn",
	"description": "Deal 2 damage to all enemy minions. Restore all friendly minions to full Health.",
	"manaCost": 4,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20132,
	"faction": "Vetruvian Imperium",
	"rarity": "Epic",
	"name": "Auroras Tears",
	"description": "This turn, your General gains +2 Attack for every equipped artifact.",
	"manaCost": 1,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20133,
	"faction": "Abyssian Host",
	"rarity": "Legendary",
	"name": "Deathfire Crescendo",
	"description": "Give a friendly minion, \"Deathwatch: Gains +2/+2.\"",
	"manaCost": 3,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20134,
	"faction": "Vanar Kindred",
	"rarity": "Basic",
	"name": "Chromatic Cold",
	"description": "Dispel a space. Deal 2 damage to the enemy minion or General on that space.",
	"manaCost": 2,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20135,
	"faction": "Vanar Kindred",
	"rarity": "Basic",
	"name": "Frostfire",
	"description": "Give a friendly minion +3 Attack. If it is Vespyr, also give it +3 Health.",
	"manaCost": 2,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20136,
	"faction": "Vanar Kindred",
	"rarity": "Basic",
	"name": "Avalanche",
	"description": "Deal 4 damage to ALL minions and Generals on your starting side of the battlefield and Stun them.",
	"manaCost": 4,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20137,
	"faction": "Vanar Kindred",
	"rarity": "Epic",
	"name": "Boundless Courage",
	"description": "Give a friendly minion +2 Attack. It takes no damage this turn.",
	"manaCost": 2,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20138,
	"faction": "Vanar Kindred",
	"rarity": "Rare",
	"name": "Mesmerize",
	"description": "Next turn, your opponent's minions cost 1 more to summon.",
	"manaCost": 1,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20139,
	"faction": "Vanar Kindred",
	"rarity": "Basic",
	"name": "Flash Freeze",
	"description": "Deal 1 damage to a minion and Stun it.",
	"manaCost": 0,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20140,
	"faction": "Vanar Kindred",
	"rarity": "Rare",
	"name": "Mark of Solitude",
	"description": "One minion becomes 5/5. It can no longer attack Generals.",
	"manaCost": 2,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20141,
	"faction": "Songhai Empire",
	"rarity": "Basic",
	"name": "Kage Lightning",
	"description": "Deal 5 damage to an enemy minion.",
	"manaCost": 2,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20143,
	"faction": "Songhai Empire",
	"rarity": "Legendary",
	"name": "Eight Gates",
	"description": "Spells you cast this turn that deal damage deal +2 damage.",
	"manaCost": 2,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20144,
	"faction": "Vanar Kindred",
	"rarity": "Basic",
	"name": "Aspect of the Fox",
	"description": "Transform ANY minion into a 3/3 Ravager with no abilities.",
	"manaCost": 1,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20145,
	"faction": "Vanar Kindred",
	"rarity": "Epic",
	"name": "Aspect of the Drake",
	"description": "Transform ANY minion into a 4/4 Whyte Drake with Flying. All friendly minions nearby it gain Flying.",
	"manaCost": 4,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20146,
	"faction": "Vanar Kindred",
	"rarity": "Legendary",
	"name": "Aspect of the Mountains",
	"description": "Transform ANY minion into a 5/5 Seismic Elemental. Deal 5 damage to enemy minions around it.",
	"manaCost": 6,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20147,
	"faction": "Vanar Kindred",
	"rarity": "Legendary",
	"name": "Gravity Well",
	"description": "Summon four joined 0/1 Walls with Provoke.",
	"manaCost": 2,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20148,
	"faction": "Vanar Kindred",
	"rarity": "Rare",
	"name": "Blazing Spines",
	"description": "Summon two joined 3/3 Walls that can attack.",
	"manaCost": 3,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20149,
	"faction": "Vanar Kindred",
	"rarity": "Common",
	"name": "Bonechill Barrier",
	"description": "Summon three joined 0/2 Vespyr Walls.  Minions that attack these walls are Stunned.",
	"manaCost": 2,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20150,
	"faction": "Vanar Kindred",
	"rarity": "Common",
	"name": "Polarity",
	"description": "Switch ANY minion's Attack and Health.",
	"manaCost": 0,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20151,
	"faction": "Vetruvian Imperium",
	"rarity": "Common",
	"name": "Bone Swarm",
	"description": "Deal 2 damage to the enemy General and all enemy minions around them.",
	"manaCost": 2,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20152,
	"faction": "Vetruvian Imperium",
	"rarity": "Rare",
	"name": "Fountain of Youth",
	"description": "Restore all friendly minions to full Health.",
	"manaCost": 2,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20153,
	"faction": "Vetruvian Imperium",
	"rarity": "Rare",
	"name": "Inner Oasis",
	"description": "Give all friendly minions +3 Health. Draw a card.",
	"manaCost": 3,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20154,
	"faction": "Abyssian Host",
	"rarity": "Epic",
	"name": "Rite Of The Undervault",
	"description": "Draw to fill your action bar.",
	"manaCost": 5,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20155,
	"faction": "Songhai Empire",
	"rarity": "Legendary",
	"name": "Heaven's Eclipse",
	"description": "Draw 3 spell cards from your deck.",
	"manaCost": 5,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20156,
	"faction": "Magmar Aspects",
	"rarity": "Epic",
	"name": "Mind Steal",
	"description": "Steal a random minion from your opponent's deck and summon it.",
	"manaCost": 4,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20157,
	"faction": "Magmar Aspects",
	"rarity": "Rare",
	"name": "Egg Morph",
	"description": "Turn a non-Egg minion into an Egg, or hatch an Egg.",
	"manaCost": 4,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20158,
	"faction": "Lyonar Kingdoms",
	"rarity": "Epic",
	"name": "Aerial Rift",
	"description": "Give your minions Airdrop this turn.  Draw a card.",
	"manaCost": 1,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20160,
	"faction": "Vanar Kindred",
	"rarity": "Common",
	"name": "Hailstone Prison",
	"description": "Return ANY minion to its action bar.",
	"manaCost": 2,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20161,
	"faction": "Lyonar Kingdoms",
	"rarity": "Rare",
	"name": "Magnetize",
	"description": "Pull ANY minion to the space in front of your General.",
	"manaCost": 1,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20162,
	"faction": "Magmar Aspects",
	"rarity": "Rare",
	"name": "Kinetic Equilibrium",
	"description": "Deal 2 damage to ALL minions in a 3x3 area. Friendly minions in the area gain +2 Attack.",
	"manaCost": 3,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20163,
	"faction": "Vanar Kindred",
	"rarity": "Epic",
	"name": "Spirit of the Wild",
	"description": "Reactivate friendly minions on your opponent's starting side of the battlefield.",
	"manaCost": 4,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20165,
	"faction": "Vanar Kindred",
	"rarity": "Common",
	"name": "Cryogenesis",
	"description": "Deal 4 damage to an enemy minion. Draw a Vespyr minion from your deck.",
	"manaCost": 3,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20166,
	"faction": "Abyssian Host",
	"rarity": "Epic",
	"name": "Consuming Rebirth",
	"description": "Destroy a friendly minion. At the end of your turn, re-summon it on the same space and give it +1/+1.",
	"manaCost": 2,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20167,
	"faction": "Songhai Empire",
	"rarity": "Rare",
	"name": "Mist Walking",
	"description": "Teleport your General up to 2 spaces.",
	"manaCost": 1,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20102,
	"faction": "Songhai Empire",
	"rarity": "Basic",
	"name": "Killing Edge",
	"description": "Give a friendly minion +4/+2. If that minion has Backstab, draw a card at end of turn.",
	"manaCost": 3,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20224,
	"faction": "Neutral",
	"rarity": "Basic",
	"name": "Riddle",
	"description": "While you have the Riddle, you cannot replace. Cast to give your opponent a Riddle.",
	"manaCost": 2,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 30001,
	"faction": "Lyonar Kingdoms",
	"rarity": "Epic",
	"name": "Skywind Glaives",
	"description": "Friendly minions nearby your General gain +2 Attack.",
	"manaCost": 3,
	"type": "Artifact",
	"race": "Artifact",
	"set": "Base"
}, {
	"id": 30002,
	"faction": "Abyssian Host",
	"rarity": "Legendary",
	"name": "Soul Grimwar",
	"description": "Your General gains, \"Deathwatch: Gains +2 Attack.\"",
	"manaCost": 3,
	"type": "Artifact",
	"race": "Artifact",
	"set": "Base"
}, {
	"id": 30004,
	"faction": "Lyonar Kingdoms",
	"rarity": "Basic",
	"name": "Sunstone Bracers",
	"description": "Your General gains +1 Attack.",
	"manaCost": 0,
	"type": "Artifact",
	"race": "Artifact",
	"set": "Base"
}, {
	"id": 30005,
	"faction": "Abyssian Host",
	"rarity": "Basic",
	"name": "Horn of the Forsaken",
	"description": "Whenever your General damages an enemy minion or General, summon a 1/1 Wraithling on a random nearby space.",
	"manaCost": 1,
	"type": "Artifact",
	"race": "Artifact",
	"set": "Base"
}, {
	"id": 30006,
	"faction": "Vetruvian Imperium",
	"rarity": "Basic",
	"name": "Staff Of Y'Kir",
	"description": "Your General gains +2 Attack.",
	"manaCost": 2,
	"type": "Artifact",
	"race": "Artifact",
	"set": "Base"

}, {
	"id": 30007,
	"faction": "Songhai Empire",
	"rarity": "Legendary",
	"name": "Mask of Shadows",
	"description": "Your General gains Backstab (4).",
	"manaCost": 2,
	"type": "Artifact",
	"race": "Artifact",
	"set": "Base"
}, {
	"id": 30008,
	"faction": "Vetruvian Imperium",
	"rarity": "Epic",
	"name": "Wildfire Ankh",
	"description": "Your General gains Blast.",
	"manaCost": 3,
	"type": "Artifact",
	"race": "Artifact",
	"set": "Base"
}, {
	"id": 30009,
	"faction": "Songhai Empire",
	"rarity": "Epic",
	"name": "Cyclone Mask",
	"description": "Your General gains Ranged.",
	"manaCost": 3,
	"type": "Artifact",
	"race": "Artifact",
	"set": "Base"
}, {
	"id": 30010,
	"faction": "Songhai Empire",
	"rarity": "Basic",
	"name": "Bloodrage Mask",
	"description": "Whenever you cast a spell, deal 1 damage to the enemy General.",
	"manaCost": 1,
	"type": "Artifact",
	"race": "Artifact",
	"set": "Base"
}, {
	"id": 30011,
	"faction": "Vetruvian Imperium",
	"rarity": "Legendary",
	"name": "Hexblade",
	"description": "Your General gains +3 Attack. Whenever your General damages an enemy minion, its Attack becomes 1.",
	"manaCost": 4,
	"type": "Artifact",
	"race": "Artifact",
	"set": "Base"
}, {
	"id": 30012,
	"faction": "Magmar Aspects",
	"rarity": "Basic",
	"name": "Adamantite Claws",
	"description": "Your General gains +4 Attack.",
	"manaCost": 4,
	"type": "Artifact",
	"race": "Artifact",
	"set": "Base"
}, {
	"id": 30013,
	"faction": "Magmar Aspects",
	"rarity": "Epic",
	"name": "Iridium Scale",
	"description": "Your General gains Frenzy.",
	"manaCost": 2,
	"type": "Artifact",
	"race": "Artifact",
	"set": "Base"
}, {
	"id": 30014,
	"faction": "Abyssian Host",
	"rarity": "Epic",
	"name": "Spectral Blade",
	"description": "Your General gains +2 Attack. Whenever your General destroys an enemy minion, restore 2 Health to your General.",
	"manaCost": 2,
	"type": "Artifact",
	"race": "Artifact",
	"set": "Base"
}, {
	"id": 30015,
	"faction": "Vanar Kindred",
	"rarity": "Basic",
	"name": "Snowpiercer",
	"description": "Your General gains +3 Attack.",
	"manaCost": 3,
	"type": "Artifact",
	"race": "Artifact",
	"set": "Base"
}, {
	"id": 30016,
	"faction": "Vanar Kindred",
	"rarity": "Legendary",
	"name": "Coldbiter",
	"description": "At the end of your turn, your General deals 2 damage to each enemy minion around them.",
	"manaCost": 2,
	"type": "Artifact",
	"race": "Artifact",
	"set": "Base"
}, {
	"id": 30017,
	"faction": "Magmar Aspects",
	"rarity": "Legendary",
	"name": "Twin Fang",
	"description": "Whenever a friendly minion or your General takes damage, your General gains +2 Attack.",
	"manaCost": 3,
	"type": "Artifact",
	"race": "Artifact",
	"set": "Base"
}, {
	"id": 30018,
	"faction": "Lyonar Kingdoms",
	"rarity": "Legendary",
	"name": "Arclyte Regalia",
	"description": "Your General gains +2 Attack. The first time your General takes damage each turn, prevent 2 of it.",
	"manaCost": 4,
	"type": "Artifact",
	"race": "Artifact",
	"set": "Base"
}, {
	"id": 30019,
	"faction": "Vanar Kindred",
	"rarity": "Epic",
	"name": "Winterblade",
	"description": "Your General gains +2 Attack. Enemy minions damaged by your General are Stunned.",
	"manaCost": 4,
	"type": "Artifact",
	"race": "Artifact",
	"set": "Base"
}]
