[{
	"id": 1,
	"faction": "Lyonar Kingdoms",
	"rarity": "Basic",
	"name": "Argeon Highmayne",
	"description": "Bloodborn Spell: Give a minion nearby your General +2 Attack.",
	"manaCost": 0,
	"type": "Unit",
	"race": "General",
	"attack": 2,
	"health": 25,
	"set": "Base"
}, {
	"id": 10,
	"faction": "Lyonar Kingdoms",
	"rarity": "Epic",
	"name": "Sunstone Templar",
	"description": "Whenever this attacks or counterattacks, it dispels that enemy.",
	"manaCost": 2,
	"type": "Unit",
	"race": "Minion",
	"attack": 1,
	"health": 4,
	"set": "Base"
}, {
	"id": 20,
	"faction": "Lyonar Kingdoms",
	"rarity": "Legendary",
	"name": "Grandmaster Z'ir",
	"description": "When your General dies, Grandmaster Z'ir becomes your General.",
	"manaCost": 7,
	"type": "Unit",
	"race": "Minion",
	"attack": 5,
	"health": 12,
	"set": "Base"
}, {
	"id": 101,
	"faction": "Songhai Empire",
	"rarity": "Basic",
	"name": "Kaleos Xaan",
	"description": "Bloodborn Spell: Move a friendly minion up to 2 spaces.",
	"manaCost": 0,
	"type": "Unit",
	"race": "General",
	"attack": 2,
	"health": 25,
	"set": "Base"
}, {
	"id": 121,
	"faction": "Songhai Empire",
	"rarity": "Legendary",
	"name": "Tusk Boar",
	"description": "Rush\nReturn this minion to your action bar at the beginning of your turn.",
	"manaCost": 2,
	"type": "Unit",
	"race": "Minion",
	"attack": 2,
	"health": 3,
	"set": "Base"
}, {
	"id": 201,
	"faction": "Vetruvian Imperium",
	"rarity": "Basic",
	"name": "Zirix Starstrider",
	"description": "Bloodborn Spell: Summon a 2/2 Wind Dervish on a random space nearby.",
	"manaCost": 0,
	"type": "Unit",
	"race": "General",
	"attack": 2,
	"health": 25,
	"set": "Base"
}, {
	"id": 209,
	"faction": "Vetruvian Imperium",
	"rarity": "Common",
	"name": "Starfire Scarab",
	"description": "Blast",
	"manaCost": 5,
	"type": "Unit",
	"race": "Minion",
	"attack": 4,
	"health": 6,
	"set": "Base"
}, {
	"id": 215,
	"faction": "Vetruvian Imperium",
	"rarity": "Rare",
	"name": "Fireblaze Obelysk",
	"description": "Summon Dervish\nYour Dervishes have +1 Attack.",
	"manaCost": 3,
	"type": "Unit",
	"race": "Structure",
	"attack": 0,
	"health": 6,
	"set": "Base"
}, {
	"id": 216,
	"faction": "Vetruvian Imperium",
	"rarity": "Common",
	"name": "Windstorm Obelysk",
	"description": "Summon Dervish\nYour Dervishes have +1 Health.",
	"manaCost": 3,
	"type": "Unit",
	"race": "Structure",
	"attack": 0,
	"health": 6,
	"set": "Base"
}, {
	"id": 222,
	"faction": "Vetruvian Imperium",
	"rarity": "Legendary",
	"name": "Oserix",
	"description": "Flying\nDying Wish: Equip 2 random artifacts from your deck.",
	"manaCost": 7,
	"type": "Unit",
	"race": "Minion",
	"attack": 8,
	"health": 6,
	"set": "Base"
}, {
	"id": 301,
	"faction": "Abyssian Host",
	"rarity": "Basic",
	"name": "Lilithe Blightchaser",
	"description": "Bloodborn Spell: Summon 2 Wraithlings nearby your General.",
	"manaCost": 0,
	"type": "Unit",
	"race": "General",
	"attack": 2,
	"health": 25,
	"set": "Base"
}, {
	"id": 309,
	"faction": "Abyssian Host",
	"rarity": "Common",
	"name": "Abyssal Juggernaut",
	"description": "Whenever this minion destroys an enemy minion, turn that space into Shadow Creep.",
	"manaCost": 4,
	"type": "Unit",
	"race": "Minion",
	"attack": 4,
	"health": 5,
	"set": "Base"
}, {
	"id": 310,
	"faction": "Abyssian Host",
	"rarity": "Rare",
	"name": "Bloodmoon Priestess",
	"description": "Deathwatch: Summon a Wraithling on a random nearby space.",
	"manaCost": 4,
	"type": "Unit",
	"race": "Minion",
	"attack": 3,
	"health": 3,
	"set": "Base"
}, {
	"id": 322,
	"faction": "Abyssian Host",
	"rarity": "Epic",
	"name": "Reaper of the Nine Moons",
	"description": "Flying\nDying Wish: Summon a random minion from the opponent's deck on this space.",
	"manaCost": 5,
	"type": "Unit",
	"race": "Minion",
	"attack": 5,
	"health": 3,
	"set": "Base"
}, {
	"id": 401,
	"faction": "Magmar Aspects",
	"rarity": "Basic",
	"name": "Vaath the Immortal",
	"description": "Bloodborn Spell: Give your General +1 Attack.",
	"manaCost": 0,
	"type": "Unit",
	"race": "General",
	"attack": 2,
	"health": 25,
	"set": "Base"
}, {
	"id": 414,
	"faction": "Magmar Aspects",
	"rarity": "Legendary",
	"name": "Silithar Elder",
	"description": "Rebirth\nAt the end of your turn, summon a Silithar Elder Egg nearby.",
	"manaCost": 7,
	"type": "Unit",
	"race": "Minion",
	"attack": 8,
	"health": 8,
	"set": "Base"
}, {
	"id": 501,
	"faction": "Vanar Kindred",
	"rarity": "Basic",
	"name": "Faie Bloodwing",
	"description": "Bloodborn Spell: Deal 2 damage to all enemies in the enemy General's Column.",
	"manaCost": 0,
	"type": "Unit",
	"race": "General",
	"attack": 2,
	"health": 25,
	"set": "Base"
}, {
	"id": 515,
	"faction": "Vanar Kindred",
	"rarity": "Legendary",
	"name": "Voice of the Wind",
	"description": "Whenever you summon a minion from your action bar, summon a 2/2 Vespyr Winter Maerid nearby.",
	"manaCost": 4,
	"type": "Unit",
	"race": "Minion",
	"attack": 4,
	"health": 4,
	"set": "Base"
}, {
	"id": 10012,
	"faction": "Neutral",
	"rarity": "Basic",
	"name": "Saberspine Tiger",
	"description": "Rush",
	"manaCost": 3,
	"type": "Unit",
	"race": "Minion",
	"attack": 3,
	"health": 2,
	"set": "Base"
}, {
	"id": 10014,
	"faction": "Neutral",
	"rarity": "Common",
	"name": "Sand Burrower",
	"description": "When this minion survives damage, it returns to your action bar.",
	"manaCost": 3,
	"type": "Unit",
	"race": "Minion",
	"attack": 2,
	"health": 4,
	"set": "Base"
}, {
	"id": 10016,
	"faction": "Neutral",
	"rarity": "Basic",
	"name": "Repulsor Beast",
	"description": "Opening Gambit: Push a nearby enemy minion to any space.",
	"manaCost": 3,
	"type": "Unit",
	"race": "Minion",
	"attack": 2,
	"health": 2,
	"set": "Base"
}, {
	"id": 10302,
	"faction": "Neutral",
	"rarity": "Rare",
	"name": "Manaforger",
	"description": "The first non-Bloodborn spell you cast each turn costs 1 less.",
	"manaCost": 2,
	"type": "Unit",
	"race": "Arcanyst",
	"attack": 1,
	"health": 3,
	"set": "Base"
}, {
	"id": 10956,
	"faction": "Neutral",
	"rarity": "Legendary",
	"name": "Red Synja",
	"description": "Whenever your General takes damage, deal 7 damage to a random nearby enemy minion.",
	"manaCost": 7,
	"type": "Unit",
	"race": "Minion",
	"attack": 7,
	"health": 7,
	"set": "Base"
}, {
	"id": 10957,
	"faction": "Neutral",
	"rarity": "Common",
	"name": "Rust Crawler",
	"description": "Opening Gambit: Destroy a random enemy artifact.",
	"manaCost": 2,
	"type": "Unit",
	"race": "Minion",
	"attack": 2,
	"health": 3,
	"set": "Base"
}, {
	"id": 10959,
	"faction": "Neutral",
	"rarity": "Common",
	"name": "Dancing Blades",
	"description": "Opening Gambit: Deal 3 damage to ANY minion in front of this.",
	"manaCost": 5,
	"type": "Unit",
	"race": "Minion",
	"attack": 4,
	"health": 6,
	"set": "Base"
}, {
	"id": 10962,
	"faction": "Neutral",
	"rarity": "Epic",
	"name": "Chaos Elemental",
	"description": "Whenever this minion takes damage, it randomly teleports.",
	"manaCost": 3,
	"type": "Unit",
	"race": "Minion",
	"attack": 4,
	"health": 4,
	"set": "Base"
}, {
	"id": 10974,
	"faction": "Neutral",
	"rarity": "Epic",
	"name": "Syvrel the Exile",
	"description": "Ranged\nMinions damaged by Syvrel are pulled in front of him.",
	"manaCost": 3,
	"type": "Unit",
	"race": "Minion",
	"attack": 1,
	"health": 4,
	"set": "Base"
}, {
	"id": 10976,
	"faction": "Neutral",
	"rarity": "Epic",
	"name": "Dioltas",
	"description": "Dying Wish: Summon a 0/10 Tombstone minion with Provoke nearby your General.",
	"manaCost": 4,
	"type": "Unit",
	"race": "Minion",
	"attack": 5,
	"health": 3,
	"set": "Base"
}, {
	"id": 10989,
	"faction": "Neutral",
	"rarity": "Epic",
	"name": "Captain Hank Hart",
	"description": "Ranged\nWhenever this deals damage, restore that much Health to it.",
	"manaCost": 4,
	"type": "Unit",
	"race": "Minion",
	"attack": 2,
	"health": 4,
	"set": "Base"
}, {
	"id": 10992,
	"faction": "Neutral",
	"rarity": "Common",
	"name": "Songweaver",
	"description": "Opening Gambit: Give a nearby friendly minion +1/+1.",
	"manaCost": 3,
	"type": "Unit",
	"race": "Minion",
	"attack": 3,
	"health": 3,
	"set": "Base"
}, {
	"id": 10996,
	"faction": "Neutral",
	"rarity": "Legendary",
	"name": "Zurael, the Lifegiver",
	"description": "Opening Gambit: Summon all non-token friendly minions destroyed on your opponent's last turn on random spaces.",
	"manaCost": 7,
	"type": "Unit",
	"race": "Minion",
	"attack": 4,
	"health": 7,
	"set": "Base"
}, {
	"id": 11006,
	"faction": "Neutral",
	"rarity": "Legendary",
	"name": "Black Locust",
	"description": "Flying\nAfter this minion moves, summon a Black Locust nearby.",
	"manaCost": 4,
	"type": "Unit",
	"race": "Minion",
	"attack": 2,
	"health": 2,
	"set": "Base"
}, {
	"id": 11008,
	"faction": "Neutral",
	"rarity": "Epic",
	"name": "Mogwai",
	"description": "After this moves, draw a card.",
	"manaCost": 3,
	"type": "Unit",
	"race": "Minion",
	"attack": 2,
	"health": 3,
	"set": "Base"
}, {
	"id": 11017,
	"faction": "Neutral",
	"rarity": "Epic",
	"name": "Araki Headhunter",
	"description": "Whenever you summon a minion with Opening Gambit from your action bar, gain +2 Attack.",
	"manaCost": 2,
	"type": "Unit",
	"race": "Minion",
	"attack": 1,
	"health": 3,
	"set": "Base"
}, {
	"id": 11018,
	"faction": "Neutral",
	"rarity": "Legendary",
	"name": "Keeper of the Vale",
	"description": "Opening Gambit: Summon a random non-token friendly minion destroyed this game nearby.",
	"manaCost": 5,
	"type": "Unit",
	"race": "Minion",
	"attack": 3,
	"health": 4,
	"set": "Base"
}, {
	"id": 11022,
	"faction": "Neutral",
	"rarity": "Epic",
	"name": "Dreamgazer",
	"description": "When you replace this card, summon it nearby.  Your General takes 2 damage.",
	"manaCost": 1,
	"type": "Unit",
	"race": "Minion",
	"attack": 1,
	"health": 1,
	"set": "Base"
}, {
	"id": 11028,
	"faction": "Neutral",
	"rarity": "Rare",
	"name": "Sunsteel Defender",
	"description": "Forcefield",
	"manaCost": 4,
	"type": "Unit",
	"race": "Minion",
	"attack": 4,
	"health": 3,
	"set": "Base"
}, {
	"id": 19037,
	"faction": "Neutral",
	"rarity": "Common",
	"name": "Primus Fist",
	"description": "Opening Gambit: Give a nearby friendly minion +2 Attack this turn.",
	"manaCost": 2,
	"type": "Unit",
	"race": "Minion",
	"attack": 2,
	"health": 3,
	"set": "Base"
}, {
	"id": 19043,
	"faction": "Neutral",
	"rarity": "Legendary",
	"name": "Archon Spellbinder",
	"description": "Your opponent's non-Bloodborn spells cost 1 more to cast.",
	"manaCost": 6,
	"type": "Unit",
	"race": "Arcanyst",
	"attack": 7,
	"health": 7,
	"set": "Base"
}, {
	"id": 20050,
	"faction": "Abyssian Host",
	"rarity": "Legendary",
	"name": "Nether Summoning",
	"description": "Summon 2 non-token minions destroyed since the end of your last turn nearby.",
	"manaCost": 5,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20059,
	"faction": "Abyssian Host",
	"rarity": "Rare",
	"name": "Darkfire Sacrifice",
	"description": "Destroy a friendly minion. Your next minion costs 2 less.",
	"manaCost": 0,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20070,
	"faction": "Abyssian Host",
	"rarity": "Common",
	"name": "Grasp of Agony",
	"description": "Choose an enemy minion. When it dies, it deals 3 damage to enemies around it.",
	"manaCost": 1,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20096,
	"faction": "Vetruvian Imperium",
	"rarity": "Basic",
	"name": "Scion's Second Wish",
	"description": "Give a friendly minion +2/+2. It takes no damage from Generals.",
	"manaCost": 2,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20097,
	"faction": "Vetruvian Imperium",
	"rarity": "Legendary",
	"name": "Scion's Third Wish",
	"description": "Give a friendly Dervish minion +3/+3 and Flying.",
	"manaCost": 3,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20099,
	"faction": "Vetruvian Imperium",
	"rarity": "Epic",
	"name": "Rasha's Curse",
	"description": "Destroy a random artifact on the enemy General. Summon a Wind Dervish with Rush near them.",
	"manaCost": 2,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20105,
	"faction": "Vetruvian Imperium",
	"rarity": "Epic",
	"name": "Stars' Fury",
	"description": "Summon a Wind Dervish with Rush in front of each enemy minion and General.",
	"manaCost": 5,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20113,
	"faction": "Magmar Aspects",
	"rarity": "Common",
	"name": "Diretide Frenzy",
	"description": "Give a friendly minion +1 Attack and Frenzy.",
	"manaCost": 2,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20121,
	"faction": "Magmar Aspects",
	"rarity": "Legendary",
	"name": "Metamorphosis",
	"description": "Transform all enemy minions into 1/1 Magma with no abilities until the end of your opponent's turn.",
	"manaCost": 6,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20134,
	"faction": "Vanar Kindred",
	"rarity": "Basic",
	"name": "Chromatic Cold",
	"description": "Dispel a space. If there is an enemy minion or General on that space, deal it 2 damage.",
	"manaCost": 2,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20138,
	"faction": "Vanar Kindred",
	"rarity": "Rare",
	"name": "Mesmerize",
	"description": "Move an enemy minion or General one space.",
	"manaCost": 1,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20145,
	"faction": "Vanar Kindred",
	"rarity": "Epic",
	"name": "Aspect of the Drake",
	"description": "Transform ANY minion into a 4/4 Whyte Drake with Flying. Nearby friendly minions gain Flying.",
	"manaCost": 4,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 20162,
	"faction": "Magmar Aspects",
	"rarity": "Rare",
	"name": "Kinetic Equilibrium",
	"description": "Deal 2 damage to ALL minions in a 3x3 area. Friendly minions in the area also gain +2 Attack.",
	"manaCost": 3,
	"type": "Spell",
	"race": "Spell",
	"set": "Base"
}, {
	"id": 30005,
	"faction": "Abyssian Host",
	"rarity": "Basic",
	"name": "Horn of the Forsaken",
	"description": "Whenever your General deals damage, summon a 1/1 Wraithling nearby your General.",
	"manaCost": 1,
	"type": "Artifact",
	"race": "Artifact",
	"set": "Base"
}, {
	"id": 11033,
	"faction": "Neutral",
	"rarity": "Common",
	"name": "Arrow Whistler",
	"description": "Ranged\nYour other minions with Ranged have +1 Attack.",
	"manaCost": 4,
	"type": "Unit",
	"race": "Warmaster",
	"attack": 2,
	"health": 4,
	"set": "Base"
}, {
	"id": 11035,
	"faction": "Neutral",
	"rarity": "Rare",
	"name": "Skywing",
	"description": "Flying\nYour other minions with Flying cost 1 less.",
	"manaCost": 3,
	"type": "Unit",
	"race": "Warmaster",
	"attack": 3,
	"health": 3,
	"set": "Base"
}, {
	"id": 11036,
	"faction": "Neutral",
	"rarity": "Legendary",
	"name": "Unseven",
	"description": "Dying Wish: Summon a minion with Dying Wish from your action bar.",
	"manaCost": 4,
	"type": "Unit",
	"race": "Warmaster",
	"attack": 2,
	"health": 4,
	"set": "Base"
}, {
	"id": 11034,
	"faction": "Neutral",
	"rarity": "Epic",
	"name": "Golden Justicar",
	"description": "Provoke\nYour other minions with Provoke can move two additional spaces.",
	"manaCost": 5,
	"type": "Unit",
	"race": "Warmaster",
	"attack": 4,
	"health": 6,
	"set": "Base"
}]
