[{
	"id": 201,
	"faction": "Vetruvian Imperium",
	"rarity": "Basic",
	"name": "Zirix Starstrider",
	"description": "Bloodborn Spell: Summon a 2/2 Iron Dervish on a random space nearby your General.",
	"manaCost": 0,
	"type": "Unit",
	"race": "General",
	"attack": 2,
	"health": 25,
	"set": "Base"
}, {
	"id": 321,
	"faction": "Abyssian Host",
	"rarity": "Epic",
	"name": "Black Solus",
	"description": "Whenever you summon a Wraithling, this gains +2 Attack.",
	"manaCost": 5,
	"type": "Unit",
	"race": "Minion",
	"attack": 4,
	"health": 7,
	"set": "Base"
}, {
	"id": 417,
	"faction": "Magmar Aspects",
	"rarity": "Legendary",
	"name": "Vindicator",
	"description": "Whenever your opponent draws a card, this minion gains +2/+2.",
	"manaCost": 3,
	"type": "Unit",
	"race": "Minion",
	"attack": 1,
	"health": 3,
	"set": "Base"
}, {
	"id": 10995,
	"faction": "Neutral",
	"rarity": "Rare",
	"name": "Emerald Rejuvenator",
	"description": "Opening Gambit: Restore 4 Health to BOTH Generals.",
	"manaCost": 4,
	"type": "Unit",
	"race": "Minion",
	"attack": 4,
	"health": 4,
	"set": "Base"

}, {
	"id": 11037,
	"faction": "Neutral",
	"rarity": "Common",
	"name": "Diamond Golem",
	"description": "",
	"manaCost": 6,
	"type": "Unit",
	"race": "Golem",
	"attack": 4,
	"health": 11,
	"set": "Base"
}, {
	"id": 11038,
	"faction": "Neutral",
	"rarity": "Epic",
	"name": "Bastion",
	"description": "At the end of your turn, give other friendly minions +1 Health.",
	"manaCost": 3,
	"type": "Unit",
	"race": "Structure",
	"attack": 0,
	"health": 5,
	"set": "Base"
}, {
	"id": 11039,
	"faction": "Neutral",
	"rarity": "Rare",
	"name": "Abjudicator",
	"description": "Opening Gambit: Lower the cost of all spells in your action bar by 1.",
	"manaCost": 3,
	"type": "Unit",
	"race": "Arcanyst",
	"attack": 3,
	"health": 1,
	"set": "Base"
}, {
	"id": 11040,
	"faction": "Neutral",
	"rarity": "Legendary",
	"name": "Alter Rexx",
	"description": "Whenever you summon MECHAZ0R, put a MECHAZ0R in your action bar.",
	"manaCost": 5,
	"type": "Unit",
	"race": "Mech",
	"attack": 4,
	"health": 4,
	"set": "Base"
}, {
	"id": 24,
	"faction": "Lyonar Kingdoms",
	"rarity": "Legendary",
	"name": "Sun Sister Sterope",
	"description": "Whenever ANY minion or General is healed, put a True Strike into your action bar.",
	"manaCost": 4,
	"type": "Unit",
	"race": "Minion",
	"attack": 4,
	"health": 4,
	"set": "Base"
}, {
	"id": 124,
	"faction": "Songhai Empire",
	"rarity": "Legendary",
	"name": "Storm Sister Alkyone",
	"description": "Spells you cast that deal damage deal +1 damage.",
	"manaCost": 4,
	"type": "Unit",
	"race": "Minion",
	"attack": 3,
	"health": 5,
	"set": "Base"
}, {
	"id": 224,
	"faction": "Vetruvian Imperium",
	"rarity": "Legendary",
	"name": "Sand Sister Saon",
	"description": "Your General has +1 Attack.",
	"manaCost": 4,
	"type": "Unit",
	"race": "Minion",
	"attack": 3,
	"health": 4,
	"set": "Base"
}, {
	"id": 324,
	"faction": "Abyssian Host",
	"rarity": "Legendary",
	"name": "Shadow Sister Kelaino",
	"description": "Whenever an enemy minion or General takes damage, restore 1 Health to your General.",
	"manaCost": 4,
	"type": "Unit",
	"race": "Minion",
	"attack": 2,
	"health": 5,
	"set": "Base"
}, {
	"id": 419,
	"faction": "Magmar Aspects",
	"rarity": "Legendary",
	"name": "Earth Sister Taygete",
	"description": "Whenever this minion takes damage, deal that much damage to all nearby enemies.",
	"manaCost": 4,
	"type": "Unit",
	"race": "Minion",
	"attack": 3,
	"health": 5,
	"set": "Base"
}, {
	"id": 528,
	"faction": "Vanar Kindred",
	"rarity": "Legendary",
	"name": "Wind Sister Maia",
	"description": "Whenever you summon a minion with Infiltrate, give it +1/+1.",
	"manaCost": 4,
	"type": "Unit",
	"race": "Minion",
	"attack": 4,
	"health": 5,
	"set": "Base"
}, {
	"id": 11041,
	"faction": "Neutral",
	"rarity": "Legendary",
	"name": "Sworn Sister L'Kian",
	"description": "Opening Gambit: Add 2 random cards from your Faction to your action bar.",
	"manaCost": 4,
	"type": "Unit",
	"race": "Minion",
	"attack": 2,
	"health": 4,
	"set": "Base"
}]
