[{
		"id": 20051,
		"faction": "Abyssian Host",
		"rarity": "Basic",
		"name": "Shadow Nova",
		"description": "Turn a 2x2 area into Shadow Creep.",
		"manaCost": 4,
		"type": "Spell",
		"race": "Spell",
		"set": "Base"
	}, {
		"id": 308,
		"faction": "Abyssian Host",
		"rarity": "Basic",
		"name": "Abyssal Crawler",
		"description": "At the end of your turn, turn a nearby space into Shadow Creep.",
		"manaCost": 1,
		"type": "Unit",
		"race": "Minion",
		"attack": 2,
		"health": 1,
		"set": "Base"
	}, {
		"id": 309,
		"faction": "Abyssian Host",
		"rarity": "Common",
		"name": "Abyssal Juggernaut",
		"description": "This minion has +1/+1 for each friendly Shadow Creep.",
		"manaCost": 4,
		"type": "Unit",
		"race": "Minion",
		"attack": 3,
		"health": 3,
		"set": "Base"
	}, {
		"id": 316,
		"faction": "Abyssian Host",
		"rarity": "Rare",
		"name": "Darkspine Elemental",
		"description": "Double the damage dealt by friendly Shadow Creep.",
		"manaCost": 2,
		"type": "Unit",
		"race": "Minion",
		"attack": 1,
		"health": 4,
		"set": "Base"
	}, {
		"id": 413,
		"faction": "Magmar Aspects",
		"rarity": "Common",
		"name": "Veteran Silithar",
		"description": "Rebirth",
		"manaCost": 4,
		"type": "Unit",
		"race": "Minion",
		"attack": 4,
		"health": 3,
		"set": "Base"
	}, {
		"id": 414,
		"faction": "Magmar Aspects",
		"rarity": "Legendary",
		"name": "Silithar Elder",
		"description": "Rebirth\nAt the end of your turn, summon a Silithar Elder Egg nearby.",
		"manaCost": 7,
		"type": "Unit",
		"race": "Minion",
		"attack": 6,
		"health": 6,
		"set": "Base"
	}, {
		"id": 20068,
		"faction": "Lyonar Kingdoms",
		"rarity": "Basic",
		"name": "Divine Bond",
		"description": "Give a minion +Attack equal to its Health.",
		"manaCost": 3,
		"type": "Spell",
		"race": "Spell",
		"set": "Base"
	}, {
		"id": 20163,
		"faction": "Vanar Kindred",
		"rarity": "Epic",
		"name": "Spirit of the Wild",
		"description": "Reactivate friendly minions on your opponent's starting side of the battlefield.",
		"manaCost": 5,
		"type": "Spell",
		"race": "Spell",
		"set": "Base"
	}, {
		"id": 419,
		"faction": "Magmar Aspects",
		"rarity": "Legendary",
		"name": "Earth Sister Taygete",
		"description": "Whenever this minion takes damage, deal that much damage to all nearby enemies.",
		"manaCost": 4,
		"type": "Unit",
		"race": "Minion",
		"attack": 3,
		"health": 4,
		"set": "Base"
	}, {
		"id": 20100,
		"faction": "Songhai Empire",
		"rarity": "Common",
		"name": "Ancestral Divination",
		"description": "Draw a card for each friendly minion on the battlefield.",
		"manaCost": 4,
		"type": "Spell",
		"race": "Spell",
		"set": "Base"
	}, {
		"id": 11075,
		"faction": "Neutral",
		"rarity": "Common",
		"name": "Wood-Wen",
		"description": "Provoke\nOpening Gambit: Give a nearby friendly minion Provoke.",
		"manaCost": 2,
		"type": "Unit",
		"race": "Minion",
		"attack": 2,
		"health": 2,
		"set": "Base"
	}, {
		"id": 11076,
		"faction": "Neutral",
		"rarity": "Rare",
		"name": "Elkowl",
		"description": "Opening Gambit: Gain two random abilities.",
		"manaCost": 3,
		"type": "Unit",
		"race": "Minion",
		"attack": 2,
		"health": 3,
		"set": "Base"
	}, {
		"id": 11077,
		"faction": "Neutral",
		"rarity": "Epic",
		"name": "Grove Lion",
		"description": "While this minion is on the battlefield, your General has Forcefield.",
		"manaCost": 6,
		"type": "Unit",
		"race": "Minion",
		"attack": 5,
		"health": 5,
		"set": "Base"
	}, {
		"id": 11078,
		"faction": "Neutral",
		"rarity": "Legendary",
		"name": "Sphynx",
		"description": "Opening Gambit: Put a Riddle in your opponent's action bar.",
		"manaCost": 4,
		"type": "Unit",
		"race": "Minion",
		"attack": 5,
		"health": 4,
		"set": "Base"
	},

	{
		"id": 26,
		"faction": "Lyonar Kingdoms",
		"rarity": "Common",
		"name": "Slo",
		"description": "Provoke",
		"manaCost": 0,
		"type": "Unit",
		"race": "Battle Pet",
		"attack": 1,
		"health": 4,
		"set": "Denizens of Shim'Zar"

	}, {
		"id": 20189,
		"faction": "Lyonar Kingdoms",
		"rarity": "Epic",
		"name": "Fighting Spirit",
		"description": "Give all friendly minions +1 Health. Put a random Battle Pet into your action bar.",
		"manaCost": 1,
		"type": "Spell",
		"race": "Spell",
		"set": "Denizens of Shim'Zar"

	}, {
		"id": 25,
		"faction": "Lyonar Kingdoms",
		"rarity": "Rare",
		"name": "Fiz",
		"description": "Opening Gambit: Restore 2 Health to a minion or General.",
		"manaCost": 2,
		"type": "Unit",
		"race": "Battle Pet",
		"attack": 3,
		"health": 3,
		"set": "Denizens of Shim'Zar"
	}, {
		"id": 27,
		"faction": "Lyonar Kingdoms",
		"rarity": "Common",
		"name": "Sun Wisp",
		"description": "Opening Gambit: Draw a card.",
		"manaCost": 2,
		"type": "Unit",
		"race": "Minion",
		"attack": 2,
		"health": 1,
		"set": "Denizens of Shim'Zar"

	}, {
		"id": 20190,
		"faction": "Lyonar Kingdoms",
		"rarity": "Common",
		"name": "Lucent Beam",
		"description": "Deal 2 damage to an enemy. If a minion or General was healed this turn, deal 4 damage instead.",
		"manaCost": 2,
		"type": "Spell",
		"race": "Spell",
		"set": "Denizens of Shim'Zar"

	}, {
		"id": 28,
		"faction": "Lyonar Kingdoms",
		"rarity": "Rare",
		"name": "Radiant Dragoon",
		"description": "At the end of your turn, give a friendly minion +1 Health.",
		"manaCost": 3,
		"type": "Unit",
		"race": "Minion",
		"attack": 3,
		"health": 4,
		"set": "Denizens of Shim'Zar"
	}, {
		"id": 29,
		"faction": "Lyonar Kingdoms",
		"rarity": "Epic",
		"name": "Sunforge Lancer",
		"description": "Whenever ANY minion or General is healed, give your General +1 Attack.",
		"manaCost": 3,
		"type": "Unit",
		"race": "Minion",
		"attack": 2,
		"health": 4,
		"set": "Denizens of Shim'Zar"
	}, {
		"id": 20187,
		"faction": "Lyonar Kingdoms",
		"rarity": "Rare",
		"name": "Sky Burial",
		"description": "Destroy a minion that is not nearby any General.",
		"manaCost": 3,
		"type": "Spell",
		"race": "Spell",
		"set": "Denizens of Shim'Zar"
	}, {
		"id": 20188,
		"faction": "Lyonar Kingdoms",
		"rarity": "Common",
		"name": "Afterblaze",
		"description": "Give a friendly minion +2/+4. If that minion has Zeal, draw a card.",
		"manaCost": 3,
		"type": "Spell",
		"race": "Spell",
		"set": "Denizens of Shim'Zar"
	}, {
		"id": 20186,
		"faction": "Lyonar Kingdoms",
		"rarity": "Epic",
		"name": "Ironcliffe Heart",
		"description": "Transform a friendly minion into an Ironcliffe Guardian.",
		"manaCost": 4,
		"type": "Spell",
		"race": "Spell",
		"set": "Denizens of Shim'Zar"
	}, {
		"id": 30,
		"faction": "Lyonar Kingdoms",
		"rarity": "Legendary",
		"name": "Solarius",
		"description": "Zeal: Draw 2 additional cards at the end of your turn.",
		"manaCost": 6,
		"type": "Unit",
		"race": "Minion",
		"attack": 3,
		"health": 3,
		"set": "Denizens of Shim'Zar"
	}, {
		"id": 30024,
		"faction": "Lyonar Kingdoms",
		"rarity": "Legendary",
		"name": "Dawn's Eye",
		"description": "Your General gains +4 Attack. At the end of your turn, repair all of your artifacts to full durability.",
		"manaCost": 6,
		"type": "Artifact",
		"race": "Artifact",
		"set": "Denizens of Shim'Zar"
	}, {
		"id": 20220,
		"faction": "Lyonar Kingdoms",
		"rarity": "Legendary",
		"name": "Sky Phalanx",
		"description": "Summon three Silverguard Knights nearby your General.",
		"manaCost": 8,
		"type": "Spell",
		"race": "Spell",
		"set": "Denizens of Shim'Zar"
	}, {
		"id": 126,
		"faction": "Songhai Empire",
		"rarity": "Common",
		"name": "Ace",
		"description": "Ranged",
		"manaCost": 1,
		"type": "Unit",
		"race": "Battle Pet",
		"attack": 1,
		"health": 2,
		"set": "Denizens of Shim'Zar"
	}, {
		"id": 129,
		"faction": "Songhai Empire",
		"rarity": "Common",
		"name": "Katara",
		"description": "Backstab: (3).",
		"manaCost": 1,
		"type": "Unit",
		"race": "Minion",
		"attack": 1,
		"health": 3,
		"set": "Denizens of Shim'Zar"
	}, {
		"id": 20192,
		"faction": "Songhai Empire",
		"rarity": "Common",
		"name": "Shadow Waltz",
		"description": "Lower the cost of all minions with Backstab in your action bar by 1 and give them +1/+1.",
		"manaCost": 1,
		"type": "Spell",
		"race": "Spell",
		"set": "Denizens of Shim'Zar"
	}, {
		"id": 30023,
		"faction": "Songhai Empire",
		"rarity": "Legendary",
		"name": "Crescent Spear",
		"description": "Your General gains +1 Attack. Spells you cast that deal damage deal +1 damage.",
		"manaCost": 1,
		"type": "Artifact",
		"race": "Artifact",
		"set": "Denizens of Shim'Zar"
	}, {
		"id": 125,
		"faction": "Songhai Empire",
		"rarity": "Rare",
		"name": "Xho",
		"description": "Dying Wish: Put a random Songhai spell into your action bar. It costs 1 less.",
		"manaCost": 2,
		"type": "Unit",
		"race": "Battle Pet",
		"attack": 2,
		"health": 3,
		"set": "Denizens of Shim'Zar"
	}, {
		"id": 20191,
		"faction": "Songhai Empire",
		"rarity": "Common",
		"name": "Crimson Coil",
		"description": "Deal 2 damage to a minion. Activate your Battle Pets.",
		"manaCost": 2,
		"type": "Spell",
		"race": "Spell",
		"set": "Denizens of Shim'Zar"
	}, {
		"id": 20194,
		"faction": "Songhai Empire",
		"rarity": "Rare",
		"name": "Mirror Meld",
		"description": "Summon a copy of a friendly minion that costs 2 or less nearby.",
		"manaCost": 2,
		"type": "Spell",
		"race": "Spell",
		"set": "Denizens of Shim'Zar"
	}, {
		"id": 128,
		"faction": "Songhai Empire",
		"rarity": "Rare",
		"name": "Ki Beholder",
		"description": "Ranged\nOpening Gambit: An enemy minion cannot move next turn.",
		"manaCost": 3,
		"type": "Unit",
		"race": "Minion",
		"attack": 3,
		"health": 2,
		"set": "Denizens of Shim'Zar"
	}, {
		"id": 130,
		"faction": "Songhai Empire",
		"rarity": "Epic",
		"name": "Battle Panddo",
		"description": "Whenever this minion takes damage, deal 1 damage to all enemies.",
		"manaCost": 3,
		"type": "Unit",
		"race": "Minion",
		"attack": 2,
		"health": 4,
		"set": "Denizens of Shim'Zar"
	}, {
		"id": 20193,
		"faction": "Songhai Empire",
		"rarity": "Epic",
		"name": "Pandamonium",
		"description": "Transform ALL minions into 0/2 Panddo that cannot be attacked until end of turn.",
		"manaCost": 4,
		"type": "Spell",
		"race": "Spell",
		"set": "Denizens of Shim'Zar"
	}, {
		"id": 127,
		"faction": "Songhai Empire",
		"rarity": "Epic",
		"name": "Onyx Jaguar",
		"description": "Whenever a friendly minion is moved for any reason, give it +1/+1.",
		"manaCost": 5,
		"type": "Unit",
		"race": "Minion",
		"attack": 3,
		"health": 3,
		"set": "Denizens of Shim'Zar"
	}, {
		"id": 131,
		"faction": "Songhai Empire",
		"rarity": "Legendary",
		"name": "Grandmaster Zendo",
		"description": "The enemy General moves and attacks as if they are a Battle Pet.",
		"manaCost": 6,
		"type": "Unit",
		"race": "Minion",
		"attack": 4,
		"health": 6,
		"set": "Denizens of Shim'Zar"
	}, {
		"id": 20217,
		"faction": "Songhai Empire",
		"rarity": "Legendary",
		"name": "Koan of Horns",
		"description": "Transform all minions in your action bar and deck into 0-cost Gore Horns. Draw 3 cards.",
		"manaCost": 8,
		"type": "Spell",
		"race": "Spell",
		"set": "Denizens of Shim'Zar"
	}, {
		"id": 227,
		"faction": "Vetruvian Imperium",
		"rarity": "Common",
		"name": "Rae",
		"description": "Dying Wish: Dispel the nearest enemy minion.",
		"manaCost": 0,
		"type": "Unit",
		"race": "Battle Pet",
		"attack": 1,
		"health": 1,
		"set": "Denizens of Shim'Zar"
	}, {
		"id": 228,
		"faction": "Vetruvian Imperium",
		"rarity": "Rare",
		"name": "Pax",
		"description": "Dying Wish: Summon two 2/2 Iron Dervishes nearby.",
		"manaCost": 2,
		"type": "Unit",
		"race": "Battle Pet",
		"attack": 2,
		"health": 1,
		"set": "Denizens of Shim'Zar"
	}, {
		"id": 229,
		"faction": "Vetruvian Imperium",
		"rarity": "Rare",
		"name": "Wind Slicer",
		"description": "Opening Gambit: Lower the cost of all Structure minions in your action bar by 1.",
		"manaCost": 2,
		"type": "Unit",
		"race": "Minion",
		"attack": 2,
		"health": 3,
		"set": "Denizens of Shim'Zar"
	}, {
		"id": 20196,
		"faction": "Vetruvian Imperium",
		"rarity": "Common",
		"name": "Whisper of the Sands",
		"description": "Summon a Wind Dervish nearby each friendly Obelysk. Draw a card.",
		"manaCost": 2,
		"type": "Spell",
		"race": "Spell",
		"set": "Denizens of Shim'Zar"
	}, {
		"id": 226,
		"faction": "Vetruvian Imperium",
		"rarity": "Common",
		"name": "Falcius",
		"description": "Opening Gambit: Your General gains +2 Attack and takes no damage this turn.",
		"manaCost": 3,
		"type": "Unit",
		"race": "Minion",
		"attack": 3,
		"health": 3,
		"set": "Denizens of Shim'Zar"
	}, {
		"id": 20195,
		"faction": "Vetruvian Imperium",
		"rarity": "Common",
		"name": "Astral Flood",
		"description": "Put 3 random Battle Pets into your action bar.",
		"manaCost": 3,
		"type": "Spell",
		"race": "Spell",
		"set": "Denizens of Shim'Zar"
	}, {
		"id": 20197,
		"faction": "Vetruvian Imperium",
		"rarity": "Rare",
		"name": "Psychic Conduit",
		"description": "Take control of an enemy minion with 2 or less Attack until end of turn.",
		"manaCost": 3,
		"type": "Spell",
		"race": "Spell",
		"set": "Denizens of Shim'Zar"
	}, {
		"id": 231,
		"faction": "Vetruvian Imperium",
		"rarity": "Epic",
		"name": "Allomancer",
		"description": "Dying Wish: Summon a random Obelysk on this space.",
		"manaCost": 4,
		"type": "Unit",
		"race": "Minion",
		"attack": 4,
		"health": 3,
		"set": "Denizens of Shim'Zar"
	}, {
		"id": 232,
		"faction": "Vetruvian Imperium",
		"rarity": "Legendary",
		"name": "Nimbus",
		"description": "Whenever this minion takes damage, summon a Soulburn Obelysk nearby.",
		"manaCost": 5,
		"type": "Unit",
		"race": "Minion",
		"attack": 3,
		"health": 8,
		"set": "Denizens of Shim'Zar",
		"card": "cards/vetruvian/Nimbus.png"
	}, {
		"id": 20198,
		"faction": "Vetruvian Imperium",
		"rarity": "Epic",
		"name": "Corpse Combustion",
		"description": "Summon all friendly minions with Dying Wish destroyed since your last turn on random spaces.",
		"manaCost": 5,
		"type": "Spell",
		"race": "Spell",
		"set": "Denizens of Shim'Zar"

	}, {
		"id": 30022,
		"faction": "Vetruvian Imperium",
		"rarity": "Legendary",
		"name": "Spinecleaver",
		"description": "Your General gains +1 Attack. Enemy minions destroyed by your General summon a Bloodfire Totem on that space.",
		"manaCost": 5,
		"type": "Artifact",
		"race": "Artifact",
		"set": "Denizens of Shim'Zar"
	}, {
		"id": 233,
		"faction": "Vetruvian Imperium",
		"rarity": "Epic",
		"name": "Pantheran",
		"description": "Costs 0 if you've cast all three Scion's Wish spells this game.",
		"manaCost": 6,
		"type": "Unit",
		"race": "Minion",
		"attack": 6,
		"health": 6,
		"set": "Denizens of Shim'Zar"
	}, {
		"id": 20216,
		"faction": "Vetruvian Imperium",
		"rarity": "Legendary",
		"name": "Circle of Desiccation",
		"description": "Destroy ALL non-Structure minions.",
		"manaCost": 8,
		"type": "Spell",
		"race": "Spell",
		"set": "Denizens of Shim'Zar"
	}, {
		"id": 20201,
		"faction": "Abyssian Host",
		"rarity": "Common",
		"name": "Sphere of Darkness",
		"description": "Turn a space into Shadow Creep. Draw a card.",
		"manaCost": 1,
		"type": "Spell",
		"race": "Spell",
		"set": "Denizens of Shim'Zar"
	}, {
		"id": 326,
		"faction": "Abyssian Host",
		"rarity": "Common",
		"name": "Gor",
		"description": "Dying Wish: Summon a copy of this minion in a random unoccupied corner.",
		"manaCost": 2,
		"type": "Unit",
		"race": "Battle Pet",
		"attack": 1,
		"health": 1,
		"set": "Denizens of Shim'Zar"
	}, {
		"id": 327,
		"faction": "Abyssian Host",
		"rarity": "Rare",
		"name": "Ooz",
		"description": "Whenever this minion takes damage, turn a space occupied by an enemy into Shadow Creep.",
		"manaCost": 2,
		"type": "Unit",
		"race": "Battle Pet",
		"attack": 3,
		"health": 3,
		"set": "Denizens of Shim'Zar"
	}, {
		"id": 20199,
		"faction": "Abyssian Host",
		"rarity": "Epic",
		"name": "Lurking Fear",
		"description": "Lower the cost of all minions with Dying Wish in your action bar and deck by 1.",
		"manaCost": 2,
		"type": "Spell",
		"race": "Spell",
		"set": "Denizens of Shim'Zar"
	}, {
		"id": 20200,
		"faction": "Abyssian Host",
		"rarity": "Common",
		"name": "Inkhorn Gaze",
		"description": "Deal 2 damage to a minion. If it dies this turn, put a random Battle Pet into your action bar.",
		"manaCost": 2,
		"type": "Spell",
		"race": "Spell",
		"set": "Denizens of Shim'Zar"
	}, {
		"id": 20204,
		"faction": "Abyssian Host",
		"rarity": "Epic",
		"name": "Echoing Shriek",
		"description": "Transform ALL minions that cost 2 or less into 1/1 Wraithlings.",
		"manaCost": 2,
		"type": "Spell",
		"race": "Spell",
		"set": "Denizens of Shim'Zar"
	}, {
		"id": 328,
		"faction": "Abyssian Host",
		"rarity": "Rare",
		"name": "Blood Baronette",
		"description": "Opening Gambit: Double a nearby Wraithling's Attack and Health.",
		"manaCost": 3,
		"type": "Unit",
		"race": "Minion",
		"attack": 3,
		"health": 3,
		"set": "Denizens of Shim'Zar"
	}, {
		"id": 20205,
		"faction": "Abyssian Host",
		"rarity": "Rare",
		"name": "Void Steal",
		"description": "Give an enemy minion -3 Attack. Nearby friendly minions gain +3 Attack.",
		"manaCost": 3,
		"type": "Spell",
		"race": "Spell",
		"set": "Denizens of Shim'Zar"
	}, {
		"id": 30020,
		"faction": "Abyssian Host",
		"rarity": "Legendary",
		"name": "Ghost Azalea",
		"description": "Your General gains +1 Attack for each friendly Shadow Creep.",
		"manaCost": 4,
		"type": "Artifact",
		"race": "Artifact",
		"set": "Denizens of Shim'Zar"
	}, {
		"id": 325,
		"faction": "Abyssian Host",
		"rarity": "Common",
		"name": "Night Fiend",
		"description": "Opening Gambit: Deal 2 damage to each enemy on or near friendly Shadow Creep.",
		"manaCost": 5,
		"type": "Unit",
		"race": "Minion",
		"attack": 3,
		"health": 3,
		"set": "Denizens of Shim'Zar"
	}, {
		"id": 330,
		"faction": "Abyssian Host",
		"rarity": "Legendary",
		"name": "Klaxon",
		"description": "Provoke\nDying Wish: Turn six random spaces into Shadow Creep.",
		"manaCost": 6,
		"type": "Unit",
		"race": "Minion",
		"attack": 6,
		"health": 6,
		"set": "Denizens of Shim'Zar"
	}, {
		"id": 329,
		"faction": "Abyssian Host",
		"rarity": "Epic",
		"name": "Arcane Devourer",
		"description": "Opening Gambit: The next minion you summon this turn costs 1.",
		"manaCost": 7,
		"type": "Unit",
		"race": "Minion",
		"attack": 8,
		"health": 4,
		"set": "Denizens of Shim'Zar"
	}, {
		"id": 20213,
		"faction": "Abyssian Host",
		"rarity": "Legendary",
		"name": "Obliterate",
		"description": "Destroy all friendly Shadow Creep to deal that much damage to all enemies.",
		"manaCost": 8,
		"type": "Spell",
		"race": "Spell",
		"set": "Denizens of Shim'Zar"
	}, {
		"id": 421,
		"faction": "Magmar Aspects",
		"rarity": "Common",
		"name": "Rex",
		"description": "Rebirth",
		"manaCost": 1,
		"type": "Unit",
		"race": "Battle Pet",
		"attack": 3,
		"health": 1,
		"set": "Denizens of Shim'Zar"
	}, {
		"id": 20202,
		"faction": "Magmar Aspects",
		"rarity": "Common",
		"name": "Razor Skin",
		"description": "Give all friendly minions +1 Attack. Put a random Battle Pet into your action bar.",
		"manaCost": 1,
		"type": "Spell",
		"race": "Spell",
		"set": "Denizens of Shim'Zar"
	}, {
		"id": 20203,
		"faction": "Magmar Aspects",
		"rarity": "Common",
		"name": "Lava Lance",
		"description": " Deal 2 damage to a minion. If you have an Egg, deal 4 damage instead.",
		"manaCost": 1,
		"type": "Spell",
		"race": "Spell",
		"set": "Denizens of Shim'Zar"
	}, {
		"id": 420,
		"faction": "Magmar Aspects",
		"rarity": "Rare",
		"name": "Gro",
		"description": "Grow: +1/+1.",
		"manaCost": 2,
		"type": "Unit",
		"race": "Battle Pet",
		"attack": 2,
		"health": 4,
		"set": "Denizens of Shim'Zar"
	}, {
		"id": 423,
		"faction": "Magmar Aspects",
		"rarity": "Epic",
		"name": "Moloki Huntress",
		"description": "Grow: +1/+1.\nFriendly minions grow at the start of BOTH player's turns.",
		"manaCost": 3,
		"type": "Unit",
		"race": "Minion",
		"attack": 1,
		"health": 2,
		"set": "Denizens of Shim'Zar"
	}, {
		"id": 20218,
		"faction": "Magmar Aspects",
		"rarity": "Rare",
		"name": "Thumping Wave",
		"description": "Give a minion +5 Attack. At end of turn, transform it into a 3/3 Kin.",
		"manaCost": 3,
		"type": "Spell",
		"race": "Spell",
		"set": "Denizens of Shim'Zar"
	}, {
		"id": 422,
		"faction": "Magmar Aspects",
		"rarity": "Common",
		"name": "Wild Inceptor",
		"description": "Opening Gambit: Hatch a friendly Egg.",
		"manaCost": 4,
		"type": "Unit",
		"race": "Minion",
		"attack": 3,
		"health": 3,
		"set": "Denizens of Shim'Zar"
	}, {
		"id": 426,
		"faction": "Magmar Aspects",
		"rarity": "Epic",
		"name": "Visionar",
		"description": "Whenever ANY player draws a card, this minion gains +1/+1.",
		"manaCost": 5,
		"type": "Unit",
		"race": "Minion",
		"attack": 6,
		"health": 3,
		"set": "Denizens of Shim'Zar"
	}, {
		"id": 20206,
		"faction": "Magmar Aspects",
		"rarity": "Epic",
		"name": "Nature's Confluence",
		"description": "Summon four copies of a random Battle Pet in a 2x2 area.",
		"manaCost": 5,
		"type": "Spell",
		"race": "Spell",
		"set": "Denizens of Shim'Zar"
	}, {
		"id": 30025,
		"faction": "Magmar Aspects",
		"rarity": "Legendary",
		"name": "Morin-Khur",
		"description": "Your General gains +3 Attack. Whenever your General deals damage, hatch all friendly Eggs.",
		"manaCost": 5,
		"type": "Artifact",
		"race": "Artifact",
		"set": "Denizens of Shim'Zar"
	}, {
		"id": 424,
		"faction": "Magmar Aspects",
		"rarity": "Legendary",
		"name": "Dreadnought",
		"description": "Rebirth\nEgg minions you summon gain +2/+2.",
		"manaCost": 6,
		"type": "Unit",
		"race": "Minion",
		"attack": 4,
		"health": 6,
		"set": "Denizens of Shim'Zar"
	}, {
		"id": 20219,
		"faction": "Magmar Aspects",
		"rarity": "Legendary",
		"name": "Flaming Stampede",
		"description": "Deal 5 damage to ALL non-Egg minions and Generals.",
		"manaCost": 8,
		"type": "Spell",
		"race": "Spell",
		"set": "Denizens of Shim'Zar"
	}, {
		"id": 425,
		"faction": "Magmar Aspects",
		"rarity": "Rare",
		"name": "Mandrake",
		"description": "Costs 1 less for each minion summoned from ANY player's action bar this game.",
		"manaCost": 12,
		"type": "Unit",
		"race": "Minion",
		"attack": 6,
		"health": 6,
		"set": "Denizens of Shim'Zar"
	}, {
		"id": 20209,
		"faction": "Vanar Kindred",
		"rarity": "Epic",
		"name": "Vespyric Call",
		"description": "Put a random Vespyr minion into your action bar. It costs 1 less and has +1/+1.",
		"manaCost": 1,
		"type": "Spell",
		"race": "Spell",
		"set": "Denizens of Shim'Zar"
	}, {
		"id": 530,
		"faction": "Vanar Kindred",
		"rarity": "Common",
		"name": "Icy",
		"description": "Opening Gambit: Stun a nearby enemy minion or General.",
		"manaCost": 2,
		"type": "Unit",
		"race": "Battle Pet",
		"attack": 2,
		"health": 3,
		"set": "Denizens of Shim'Zar"
	}, {
		"id": 531,
		"faction": "Vanar Kindred",
		"rarity": "Rare",
		"name": "Bur",
		"description": "When this minion survives damage, transform it into a different Battle Pet.",
		"manaCost": 2,
		"type": "Unit",
		"race": "Battle Pet",
		"attack": 3,
		"health": 3,
		"set": "Denizens of Shim'Zar"

	}, {
		"id": 20211,
		"faction": "Vanar Kindred",
		"rarity": "Epic",
		"name": "Lightning Blitz",
		"description": "Give all friendly minions +1/+1 and randomly teleport them to your opponent's starting side of the battlefield.",
		"manaCost": 2,
		"type": "Spell",
		"race": "Spell",
		"set": "Denizens of Shim'Zar"

	}, {
		"id": 20214,
		"faction": "Vanar Kindred",
		"rarity": "Common",
		"name": "Altered Beast",
		"description": "Transform ANY minion into a random Battle Pet.",
		"manaCost": 2,
		"type": "Spell",
		"race": "Spell",
		"set": "Denizens of Shim'Zar"

	}, {
		"id": 529,
		"faction": "Vanar Kindred",
		"rarity": "Common",
		"name": "Snow Rippler",
		"description": "Infiltrate: Whenever this minion damages a General, put a random Battle Pet into your action bar.",
		"manaCost": 3,
		"type": "Unit",
		"race": "Vespyr",
		"attack": 3,
		"health": 4,
		"set": "Denizens of Shim'Zar"
	}, {
		"id": 533,
		"faction": "Vanar Kindred",
		"rarity": "Epic",
		"name": "Iceblade Dryad",
		"description": "Opening Gambit: Give a friendly Vespyr minion +1/+1 and Flying.",
		"manaCost": 3,
		"type": "Unit",
		"race": "Vespyr",
		"attack": 3,
		"health": 3,
		"set": "Denizens of Shim'Zar"
	}, {
		"id": 20208,
		"faction": "Vanar Kindred",
		"rarity": "Common",
		"name": "Wailing Overdrive",
		"description": "Give a friendly minion on your opponent's starting side of the battlefield +5/+5.",
		"manaCost": 4,
		"type": "Spell",
		"race": "Spell",
		"set": "Denizens of Shim'Zar"
	}, {
		"id": 30021,
		"faction": "Vanar Kindred",
		"rarity": "Legendary",
		"name": "White Asp",
		"description": "Your General gains +3 Attack. Whenever your General destroys a minion, summon a 3/3 Blazing Spine Wall on that space.",
		"manaCost": 4,
		"type": "Artifact",
		"race": "Artifact",
		"set": "Denizens of Shim'Zar"
	}, {
		"id": 532,
		"faction": "Vanar Kindred",
		"rarity": "Rare",
		"name": "Huldra",
		"description": "Opening Gambit: Give a friendly Vespyr minion Celerity.",
		"manaCost": 5,
		"type": "Unit",
		"race": "Minion",
		"attack": 3,
		"health": 4,
		"set": "Denizens of Shim'Zar"
	}, {
		"id": 534,
		"faction": "Vanar Kindred",
		"rarity": "Legendary",
		"name": "Frostiva",
		"description": "Forcefield\nWhenever this minion attacks or is attacked, summon a 3/3 Vespyr Night Howler nearby.",
		"manaCost": 5,
		"type": "Unit",
		"race": "Minion",
		"attack": 3,
		"health": 3,
		"set": "Denizens of Shim'Zar"
	}, {
		"id": 20207,
		"faction": "Vanar Kindred",
		"rarity": "Rare",
		"name": "Frostburn",
		"description": "Deal 3 damage to all enemy minions.",
		"manaCost": 5,
		"type": "Spell",
		"race": "Spell",
		"set": "Denizens of Shim'Zar"
	}, {
		"id": 20212,
		"faction": "Vanar Kindred",
		"rarity": "Legendary",
		"name": "Winter's Wake",
		"description": "Give all friendly Wall minions +4/+4. Those minions can now move.",
		"manaCost": 8,
		"type": "Spell",
		"race": "Spell",
		"set": "Denizens of Shim'Zar"
	}, {
		"id": 11053,
		"faction": "Neutral",
		"rarity": "Common",
		"name": "Koi",
		"description": "Takes no damage from Generals.",
		"manaCost": 1,
		"type": "Unit",
		"race": "Battle Pet",
		"attack": 3,
		"health": 1,
		"set": "Denizens of Shim'Zar"
	}, {
		"id": 11001,
		"faction": "Neutral",
		"rarity": "Common",
		"name": "Amu",
		"description": "",
		"manaCost": 2,
		"type": "Unit",
		"race": "Battle Pet",
		"attack": 3,
		"health": 3,
		"set": "Denizens of Shim'Zar"
	}, {
		"id": 11061,
		"faction": "Neutral",
		"rarity": "Epic",
		"name": "Z0r",
		"description": "Dying Wish: Put a random MECH minion into your action bar.",
		"manaCost": 2,
		"type": "Unit",
		"race": "Battle Pet",
		"attack": 2,
		"health": 1,
		"set": "Denizens of Shim'Zar"
	}, {
		"id": 11066,
		"faction": "Neutral",
		"rarity": "Rare",
		"name": "Sol",
		"description": "Opening Gambit: Activate a friendly Battle Pet.",
		"manaCost": 2,
		"type": "Unit",
		"race": "Battle Pet",
		"attack": 1,
		"health": 1,
		"set": "Denizens of Shim'Zar"
	}, {
		"id": 11004,
		"faction": "Neutral",
		"rarity": "Common",
		"name": "Yun",
		"description": "",
		"manaCost": 3,
		"type": "Unit",
		"race": "Battle Pet",
		"attack": 5,
		"health": 4,
		"set": "Denizens of Shim'Zar"
	}, {
		"id": 11051,
		"faction": "Neutral",
		"rarity": "Rare",
		"name": "Ion",
		"description": "Ranged\nDeals double damage to Generals.",
		"manaCost": 3,
		"type": "Unit",
		"race": "Battle Pet",
		"attack": 2,
		"health": 3,
		"set": "Denizens of Shim'Zar"
	}, {
		"id": 11052,
		"faction": "Neutral",
		"rarity": "Legendary",
		"name": "Hydrax",
		"description": "Whenever a friendly Battle Pet dies, draw a card.",
		"manaCost": 3,
		"type": "Unit",
		"race": "Minion",
		"attack": 3,
		"health": 3,
		"set": "Denizens of Shim'Zar"
	}, {
		"id": 11056,
		"faction": "Neutral",
		"rarity": "Common",
		"name": "Golden Mantella",
		"description": "Opening Gambit: Put a random Battle Pet into your action bar.",
		"manaCost": 3,
		"type": "Unit",
		"race": "Minion",
		"attack": 4,
		"health": 2,
		"set": "Denizens of Shim'Zar"
	}, {
		"id": 11058,
		"faction": "Neutral",
		"rarity": "Epic",
		"name": "Soboro",
		"description": "Whenever this damages a neutral minion, destroy that minion.",
		"manaCost": 3,
		"type": "Unit",
		"race": "Minion",
		"attack": 2,
		"health": 4,
		"set": "Denizens of Shim'Zar"
	}, {
		"id": 11059,
		"faction": "Neutral",
		"rarity": "Legendary",
		"name": "Zukong",
		"description": "You control your Battle Pets.",
		"manaCost": 3,
		"type": "Unit",
		"race": "Minion",
		"attack": 3,
		"health": 4,
		"set": "Denizens of Shim'Zar"
	}, {
		"id": 11057,
		"faction": "Neutral",
		"rarity": "Common",
		"name": "Gnasher",
		"description": "Dying Wish: This minion deals 3 damage to all enemies around it.",
		"manaCost": 4,
		"type": "Unit",
		"race": "Minion",
		"attack": 3,
		"health": 3,
		"set": "Denizens of Shim'Zar"
	}, {
		"id": 11054,
		"faction": "Neutral",
		"rarity": "Rare",
		"name": "Beastmaster",
		"description": "Frenzy, Celerity",
		"manaCost": 5,
		"type": "Unit",
		"race": "Minion",
		"attack": 2,
		"health": 5,
		"set": "Denizens of Shim'Zar"
	}, {
		"id": 11060,
		"faction": "Neutral",
		"rarity": "Legendary",
		"name": "Rawr",
		"description": "Whenever this minion takes damage, summon a random Battle Pet nearby.",
		"manaCost": 5,
		"type": "Unit",
		"race": "Battle Pet",
		"attack": 3,
		"health": 7,
		"set": "Denizens of Shim'Zar"
	}, {
		"id": 11063,
		"faction": "Neutral",
		"rarity": "Epic",
		"name": "Calculator",
		"description": "Opening Gambit: Gain the combined Attack and Health of all Battle Pets in your action bar.",
		"manaCost": 5,
		"type": "Unit",
		"race": "Minion",
		"attack": 1,
		"health": 1,
		"set": "Denizens of Shim'Zar"
	}, {
		"id": 11064,
		"faction": "Neutral",
		"rarity": "Legendary",
		"name": "Inquisitor Kron",
		"description": "Provoke\nWhenever you replace a card, summon a 2/2 Prisoner with a random ability nearby.",
		"manaCost": 5,
		"type": "Unit",
		"race": "Minion",
		"attack": 4,
		"health": 6,
		"set": "Denizens of Shim'Zar"
	}, {
		"id": 11055,
		"faction": "Neutral",
		"rarity": "Common",
		"name": "Silverbeak",
		"description": "",
		"manaCost": 6,
		"type": "Unit",
		"race": "Minion",
		"attack": 6,
		"health": 9,
		"set": "Denizens of Shim'Zar"
	}

]
